import { LESSON_ID_APARTMENT } from '../../core/constants.js';

export const dialogueId = 'BD::' + LESSON_ID_APARTMENT;

export const dialogue = {
  meta: {
    level: 'Pre-Intermediate',
    unit: 'Apartment & Problems',
    title: 'Apartment & Problems - Office Flat Decisions',
    emotionalTracking: true,
    tensionCurve: true,
    trapLayering: true,
    setting: 'Workplace',
  },
  startNodeId: 'a1',
  nodes: {
    a1: {
      id: 'a1',
      speaker: 'Mervat',
      ar: 'صباح الخير أحمد. في مشكلة بالشقة المؤقتة.',
      en: 'Good morning Ahmed. There is a problem in temporary flat.',
      arZ: 'Saba7 el-kheir Ahmed. Fi mushkileh bel-shaqqa el-mo2aqqateh.',
      state: 'neutral',
      tension: 1,
      choices: [
        { id: 'a1_sup', ar: 'صباح النور. شو صار بالضبط؟', en: 'Morning. What happened exactly?', arZ: 'Saba7 el-noor. Sho Sar bel-zabt?', next: 'a2' },
        { id: 'a1_neu', ar: 'صباح النور. أي جزء متعطل؟', en: 'Morning. Which part is broken?', arZ: 'Saba7 el-noor. Ay juz2 mta3aTTel?', next: 'a2b' },
        { id: 'a1_trap', ar: 'الشقة كلها مشاكل دائماً.', en: 'This flat is always problems.', arZ: 'El-shaqqa كلها مشاكل dayman.', next: 'a2c' },
      ],
    },
    a2: {
      id: 'a2',
      speaker: 'Mervat',
      ar: 'آه... في تسريب مي بالمطبخ من الليل.',
      en: 'Ah... there is water leak in kitchen since night.',
      arZ: 'Ah... fi tasreeb may bel-maTbakh men el-leil.',
      state: 'stressed',
      tension: 2,
      choices: [
        { id: 'a2_sup', ar: 'سلامتك. بنقفل المحبس فوراً.', en: 'Okay. We close the valve immediately.', arZ: 'Salamtik. Bnqaffel el-ma7بس فوراً.', next: 'a3' },
        { id: 'a2_neu', ar: 'تمام، نجيب الصيانة مباشرة.', en: 'Okay, call maintenance directly.', arZ: 'Tamaam, njeeb el-Siyaneh mobashara.', next: 'a3' },
        { id: 'a2_trap', ar: 'أكيد مبالغة صغيرة.', en: 'Sure this is small exaggeration.', arZ: 'Akeed mobalagha zghireh.', next: 'a2r' },
      ],
    },
    a2b: {
      id: 'a2b',
      speaker: 'Mervat',
      ar: 'على سيرة المطبخ، الخزانة تحت المجلى تبللت.',
      en: 'Speaking of kitchen, cabinet under sink got wet.',
      arZ: '3ala seeret el-maTbakh, el-khazaneh ta7t el-majla taballalet.',
      state: 'neutral',
      tension: 2,
      choices: [
        { id: 'a2b_sup', ar: 'منيح عرفنا بدري. نمنع الضرر.', en: 'Good we knew early. Prevent more damage.', arZ: 'Mnee7 3erefna badri. Nmna3 el-Darar.', next: 'a3' },
        { id: 'a2b_neu', ar: 'تمام، بنوثق الصور أول.', en: 'Okay, document photos first.', arZ: 'Tamaam, bnwaththiq el-Sowar awwal.', next: 'a3' },
        { id: 'a2b_trap', ar: 'خزانة بسيطة، ما بتفرق.', en: 'Just cabinet, not important.', arZ: 'Khazaneh baseeTah, ma btifra2.', next: 'a2r' },
      ],
    },
    a2c: {
      id: 'a2c',
      speaker: 'Mervat',
      ar: 'يعني... هيك بنصير نتأخر كل مرة.',
      en: 'I mean... this way we get delayed every time.',
      arZ: 'Ya3ni... heik bnSeer nta2akhar kol marra.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 'a2c_rep', ar: 'معك حق، آسف. خلينا نحلها بسرعة.', en: 'You are right, sorry. Let us fix quickly.', arZ: 'Ma3ik 7a2, asef. Khallina n7ellha b-ser3a.', next: 'a3' },
        { id: 'a2c_neu', ar: 'تمام، شو أول خطوة؟', en: 'Okay, what is first step?', arZ: 'Tamaam, sho awwal khotweh?', next: 'a3' },
      ],
    },
    a2r: {
      id: 'a2r',
      speaker: 'Mervat',
      ar: 'طيب... تجاهل التسريب ممكن يخرب الكهربا.',
      en: 'Okay... ignoring leak can damage electricity.',
      arZ: 'Tayyeb... تجاهل el-tasreeb momkin ykharrib el-kahraba.',
      state: 'stressed',
      tension: 4,
      choices: [
        { id: 'a2r_rep', ar: 'صح. السلامة أولاً، نتحرك هلق.', en: 'Right. Safety first, we move now.', arZ: 'Sa7. El-salameh awwalan, nte7arrak halla2.', next: 'a3' },
        { id: 'a2r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 'a_end_awk' },
      ],
    },
    a3: {
      id: 'a3',
      speaker: 'Kareem',
      ar: 'مقاطعة: صاحب البناية اتصل، بده تقرير فوري.',
      en: 'Interruption: building owner called, wants immediate report.',
      arZ: 'Moqata3a: Sa7eb el-binaayi ittaSal, بدو taqreer fawri.',
      state: 'stressed',
      tension: 3,
      choices: [
        { id: 'a3_sup', ar: 'تمام، أنا بكتب التقرير بسرعة.', en: 'Okay, I write report quickly.', arZ: 'Tamaam, ana bktob el-taqreer b-ser3a.', next: 'a4' },
        { id: 'a3_neu', ar: 'منيح، نعطيه وصف دقيق.', en: 'Good, give him precise description.', arZ: 'Mnee7, n3Teeh waSf daqeeq.', next: 'a4' },
        { id: 'a3_trap', ar: 'خليه يستنى شوي.', en: 'Let him wait a bit.', arZ: 'Khallih yistanna shway.', next: 'a3r' },
      ],
    },
    a3r: {
      id: 'a3r',
      speaker: 'Mervat',
      ar: 'استنى... إذا تأخرنا، ممكن يرفض الإصلاح.',
      en: 'Wait... if delayed, he may refuse repair.',
      arZ: 'Istanna... iza ta2akharna, momkin yirfoD el-iSla7.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'a3r_rep', ar: 'معك حق. نبلغه الآن.', en: 'You are right. Inform him now.', arZ: 'Ma3ik 7a2. Nballigho el-aan.', next: 'a4' },
        { id: 'a3r_neu', ar: 'تمام، شو نحكي أول جملة؟', en: 'Okay, what is first sentence?', arZ: 'Tamaam, sho ne7ki awwal jomleh?', next: 'a4' },
      ],
    },
    a4: {
      id: 'a4',
      speaker: 'Mervat',
      ar: 'في شغلة صغيرة: بتراجع نص الشكوى؟',
      en: 'Small request: can you review complaint text?',
      arZ: 'Fi shaghleh zghireh: btraje3 naSS el-shakwa?',
      state: 'neutral',
      tension: 3,
      choices: [
        { id: 'a4_sup', ar: 'أكيد. بصيغها رسمي وواضح.', en: 'Sure. I draft it formal and clear.', arZ: 'Akeed. BSooghha رسمي w wade7.', next: 'a5' },
        { id: 'a4_neu', ar: 'بعد دقيقة ببعث نسخة معدلة.', en: 'After one minute I send edited copy.', arZ: 'Ba3d da2ee2a bab3at nuskha mo3addaleh.', next: 'a5b' },
        { id: 'a4_trap', ar: 'هاي شغلتك مش شغلتي.', en: 'This is your job not mine.', arZ: 'Hay shoghltek mish shoghlti.', next: 'a4r' },
      ],
    },
    a4r: {
      id: 'a4r',
      speaker: 'Mervat',
      ar: 'أنا بحتاج بس مراجعة لغوية سريعة.',
      en: 'I only need a quick language review.',
      arZ: 'Ana ba7taj bas moraja3a loغawiyyeh saree3a.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'a4r_rep', ar: 'معك حق، براجعها حالاً.', en: 'You are right, I review now.', arZ: 'Ma3ik 7a2, braje3ha 7alan.', next: 'a5' },
        { id: 'a4r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 'a_end_awk' },
      ],
    },
    a5: {
      id: 'a5',
      speaker: 'Mervat',
      ar: 'ممتاز. شكواك كانت واضحة ومقنعة.',
      en: 'Great. Your complaint text was clear and convincing.',
      arZ: 'Momtaz. Shakwak kanet wade7a w moqni3a.',
      state: 'relaxed',
      tension: 2,
      choices: [
        { id: 'a5_sup', ar: 'حلو. ونضيف صور التسريب كدليل.', en: 'Nice. Add leak photos as evidence.', arZ: '7elw. W nDeef Sowar el-tasreeb ka-daleel.', next: 'a6' },
        { id: 'a5_neu', ar: 'تمام، نرسلها لصاحب البناية.', en: 'Okay, send it to building owner.', arZ: 'Tamaam, nerselha le-Sa7eb el-binaayi.', next: 'a6' },
        { id: 'a5_trap', ar: 'كان ممكن نخلص بدون كل هالرسميات.', en: 'Could finish without all this formality.', arZ: 'Kan momkin nkhalles bdoon kol hal-rasmiyyat.', next: 'a5r' },
      ],
    },
    a5b: {
      id: 'a5b',
      speaker: 'Mervat',
      ar: 'أوكي... بس عامل الوقت مهم.',
      en: 'Okay... but timing factor is important.',
      arZ: 'Okay... bas 3amel el-wa2et mohem.',
      state: 'tired',
      tension: 3,
      choices: [
        { id: 'a5b_sup', ar: 'خلصت. الرسالة جاهزة للإرسال.', en: 'Done. Message is ready to send.', arZ: 'Khalast. El-risaleh jahzeh lel-ersal.', next: 'a6' },
        { id: 'a5b_neu', ar: 'تمام، نرسل الآن.', en: 'Okay, send now.', arZ: 'Tamaam, nersel el-aan.', next: 'a6' },
        { id: 'a5b_trap', ar: 'إذا تأخر الرد مش مشكلتي.', en: 'If response delayed, not my problem.', arZ: 'Iza ta2akhar el-radd mish mushkilti.', next: 'a_end_awk' },
      ],
    },
    a5r: {
      id: 'a5r',
      speaker: 'Mervat',
      ar: 'هههه... الرسميات بتحفظ حقنا قانونياً.',
      en: 'Haha... formality protects our legal rights.',
      arZ: 'Hahaha... el-rasmiyyat bt7faZ 7aqqna qanooniyyan.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 'a5r_rep', ar: 'صح، نقطة قوية.', en: 'Right, strong point.', arZ: 'Sa7, no2Ta qawiyyeh.', next: 'a6' },
        { id: 'a5r_neu', ar: 'تمام، نكمل.', en: 'Okay, continue.', arZ: 'Tamaam, nkammel.', next: 'a_end_neu' },
      ],
    },
    a6: {
      id: 'a6',
      speaker: 'Mervat',
      ar: 'انبعت التقرير، والصيانة جاية العصر.',
      en: 'Report sent and maintenance coming this afternoon.',
      arZ: 'Inba3at el-taqreer, wel-Siyaneh jaye el-3aSer.',
      state: 'warm',
      tension: 2,
      choices: [
        { id: 'a6_warm', ar: 'ممتاز. هيك أنقذنا الشقة والشغل.', en: 'Excellent. This saved flat and work.', arZ: 'Momtaz. Heik anqaZna el-shaqqa wel-shoghl.', next: 'a_end_warm' },
        { id: 'a6_neu', ar: 'تمام، نتابع التنفيذ مساءً.', en: 'Okay, we follow execution in evening.', arZ: 'Tamaam, nتابع el-tanfeeth masa2an.', next: 'a_end_neu' },
        { id: 'a6_trap', ar: 'المهم خلصنا بسرعة.', en: 'Important is we finished quickly.', arZ: 'El-mohem khalasna b-ser3a.', next: 'a_end_neu' },
      ],
    },
    a_end_warm: {
      id: 'a_end_warm',
      speaker: 'Mervat',
      ar: 'يعطيك العافية يا أحمد. شغل مرتب.',
      en: 'Thank you Ahmed. Well-organized work.',
      arZ: 'Ya3teek el-3afyeh ya Ahmed. Shoghl mratab.',
      state: 'warm',
      tension: 1,
      choices: [{ id: 'a_end_warm_c', ar: 'وإنتِ كمان.', en: 'You too.', arZ: 'W enti kaman.', next: 'END' }],
    },
    a_end_neu: {
      id: 'a_end_neu',
      speaker: 'Mervat',
      ar: 'تمام، نرجع لمهام المكتب.',
      en: 'Okay, back to office tasks.',
      arZ: 'Tamaam, narja3 le-mham el-maktab.',
      state: 'neutral',
      tension: 2,
      choices: [{ id: 'a_end_neu_c', ar: 'يلا.', en: 'Let us go.', arZ: 'Yalla.', next: 'END' }],
    },
    a_end_awk: {
      id: 'a_end_awk',
      speaker: 'Mervat',
      ar: 'طيب... أنا بكمل الموضوع لحالي.',
      en: 'Okay... I will continue this alone.',
      arZ: 'Tayyeb... ana بكمل el-mawdoo3 la7ali.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'a_end_awk_fix', ar: 'استني، آسف. نكمل مع بعض.', en: 'Wait, sorry. Let us finish together.', arZ: 'Istanni, asef. Nkammel ma3 ba3D.', next: 'a_end_neu' },
        { id: 'a_end_awk_keep', ar: 'تمام.', en: 'Fine.', arZ: 'Tamaam.', next: 'END' },
      ],
    },
    END: {
      id: 'END',
      speaker: 'System',
      ar: '✅ نهاية المشهد.',
      en: '✅ End of scene.',
      arZ: '✅ Nehayet el-mashhad.',
      state: 'neutral',
      tension: 1,
      choices: [],
    },
  },
};
