import { LESSON_ID_HEALTH } from '../../core/constants.js';

export const dialogueId = 'BD::' + LESSON_ID_HEALTH;

export const dialogue = {
  meta: {
    level: 'Pre-Intermediate',
    unit: 'Health & Emergencies',
    title: 'Health & Emergencies - Office Emergency Decisions',
    emotionalTracking: true,
    tensionCurve: true,
    trapLayering: true,
    setting: 'Workplace',
  },
  startNodeId: 'h1',
  nodes: {
    h1: {
      id: 'h1',
      speaker: 'Maya',
      ar: 'صباح الخير أحمد. جاهز نراجع خطة الطوارئ؟',
      en: 'Good morning Ahmed. Ready to review emergency plan?',
      arZ: 'Saba7 el-kheir Ahmed. Jahiz nraje3 khittet el-taware2?',
      state: 'neutral',
      tension: 1,
      choices: [
        { id: 'h1_sup', ar: 'صباح النور. أكيد، خلينا نبلش.', en: 'Morning. Sure, let us start.', arZ: 'Saba7 el-noor. Akeed, khallina nballesh.', next: 'h2' },
        { id: 'h1_neu', ar: 'صباح النور. شو أول نقطة؟', en: 'Morning. What is first point?', arZ: 'Saba7 el-noor. Sho awwal no2Ta?', next: 'h2b' },
        { id: 'h1_trap', ar: 'اليوم مزحوم، خليها لبعدين.', en: 'Today is busy, leave it for later.', arZ: 'El-yom maz7oom, khalliha la-ba3deen.', next: 'h2c' },
      ],
    },
    h2: {
      id: 'h2',
      speaker: 'Maya',
      ar: 'آه... منيحة، بس في صداع خفيف اليوم.',
      en: 'Ah... I am okay, but slight headache today.',
      arZ: 'Ah... mnee7a, bas fi soda3 khafeef el-yom.',
      state: 'tired',
      tension: 2,
      choices: [
        { id: 'h2_sup', ar: 'سلامتك. إذا بدك أنا بعطي التعليمات.', en: 'Hope you are well. I can lead instructions.', arZ: 'Salamtik. Iza biddik ana ba3Ti el-ta3leemat.', next: 'h3' },
        { id: 'h2_neu', ar: 'تمام، نراجع بسرعة ونرتاح.', en: 'Okay, review quickly then rest.', arZ: 'Tamaam, nraje3 b-ser3a w nerta7.', next: 'h3' },
        { id: 'h2_trap', ar: 'صداع بسيط، مش مشكلة كبيرة.', en: 'Just headache, not a big issue.', arZ: 'Soda3 baseeT, mish mushkileh kbeereh.', next: 'h2r' },
      ],
    },
    h2b: {
      id: 'h2b',
      speaker: 'Maya',
      ar: 'قبل ما نكمل، بدنا نثبت أرقام الإسعاف.',
      en: 'Before we continue, we need to confirm emergency numbers.',
      arZ: 'Qabel ma nkammel, badna nthabbit arqam el-is3af.',
      state: 'neutral',
      tension: 2,
      choices: [
        { id: 'h2b_sup', ar: 'ممتاز. أنا بتأكد من اللوحة.', en: 'Great. I will verify board numbers.', arZ: 'Momtaz. Ana bat2akkad men el-lo7a.', next: 'h3' },
        { id: 'h2b_neu', ar: 'تمام، ومعها مخارج الطوارئ.', en: 'Okay, and emergency exits too.', arZ: 'Tamaam, w ma3ha makharej el-taware2.', next: 'h3' },
        { id: 'h2b_trap', ar: 'كلنا حافظين الأرقام.', en: 'We all know the numbers.', arZ: 'Kollna 7afzeen el-arqam.', next: 'h2r' },
      ],
    },
    h2c: {
      id: 'h2c',
      speaker: 'Maya',
      ar: 'يعني... التأجيل خطر. الأسبوع الماضي صار إغماء.',
      en: 'I mean... delaying is risky. Last week we had fainting.',
      arZ: 'Ya3ni... el-ta2jeel khaTar. El-osboo3 el-maDi Sar ighma2.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 'h2c_rep', ar: 'معك حق، آسف. نراجعها الآن.', en: 'You are right, sorry. Let us review now.', arZ: 'Ma3ik 7a2, asef. Nraje3ha el-aan.', next: 'h3' },
        { id: 'h2c_neu', ar: 'تمام، شو المطلوب أول؟', en: 'Okay, what is needed first?', arZ: 'Tamaam, sho el-matloub awwal?', next: 'h3' },
      ],
    },
    h2r: {
      id: 'h2r',
      speaker: 'Maya',
      ar: 'طيب... وقت الطوارئ بننسى أبسط التفاصيل.',
      en: 'Okay... in emergencies we forget simple details.',
      arZ: 'Tayyeb... wa2et el-taware2 bninsa absaT el-tafaseel.',
      state: 'stressed',
      tension: 4,
      choices: [
        { id: 'h2r_rep', ar: 'صح، خلينا نعملها بطريقة عملية.', en: 'Right, let us do it practically.', arZ: 'Sa7, khallina na3melha b-Taree2a 3amaliyyeh.', next: 'h3' },
        { id: 'h2r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 'h_end_awk' },
      ],
    },
    h3: {
      id: 'h3',
      speaker: 'Omar',
      ar: 'مقاطعة: سامر دوّخ فجأة جنب المطبخ.',
      en: 'Interruption: Samer got dizzy near kitchen.',
      arZ: 'Moqata3a: Samer dawwakh faj2eh janb el-maTbakh.',
      state: 'stressed',
      tension: 3,
      choices: [
        { id: 'h3_sup', ar: 'أنا بروح معه فوراً. إنتِ جيبي المي.', en: 'I go to him now. You bring water.', arZ: 'Ana بروح ma3o فوراً. Enti jeebi el-may.', next: 'h4' },
        { id: 'h3_neu', ar: 'تمام، خلينا نهديه ونجلسه.', en: 'Okay, let us calm him and seat him.', arZ: 'Tamaam, khallina nhaddeeh w نجلسه.', next: 'h4' },
        { id: 'h3_trap', ar: 'أكيد تمثيل، بيصير معه دايماً.', en: 'Sure pretending, happens with him always.', arZ: 'Akeed tamtheel, bySeer ma3o dayman.', next: 'h3r' },
      ],
    },
    h3r: {
      id: 'h3r',
      speaker: 'Maya',
      ar: 'استنى... هاد خطر. ما منستهين بأي عرض.',
      en: 'Wait... this is risky. We do not ignore symptoms.',
      arZ: 'Istanna... had khaTar. Ma mnistahyeen b-ay 3araD.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'h3r_rep', ar: 'معك حق. خلينا نتصرف صح الآن.', en: 'You are right. Let us act correctly now.', arZ: 'Ma3ik 7a2. Khallina netsaRraf sa7 el-aan.', next: 'h4' },
        { id: 'h3r_neu', ar: 'تمام، شو أول خطوة؟', en: 'Okay, what is first step?', arZ: 'Tamaam, sho awwal khotweh?', next: 'h4' },
      ],
    },
    h4: {
      id: 'h4',
      speaker: 'Maya',
      ar: 'آه... سامر متوتر، وتنفسه سريع شوي.',
      en: 'Ah... Samer is tense, his breathing is a bit fast.',
      arZ: 'Ah... Samer mtawatter, w tanaffoso saree3 shway.',
      state: 'stressed',
      tension: 4,
      choices: [
        { id: 'h4_sup', ar: 'طيب اسمع، بناخده مكان هادي فوراً.', en: 'Okay listen, we move him to calm place now.', arZ: 'Tayyeb esma3, بناخده makan hadi فوراً.', next: 'h5' },
        { id: 'h4_neu', ar: 'تمام، بخليه يقعد ويتنفس ببطء.', en: 'Okay, I seat him and slow breathing.', arZ: 'Tamaam, bakhalleh ye2od w yitnaffas b-buT2.', next: 'h5' },
        { id: 'h4_trap', ar: 'خليه يشرب قهوة وبيتحسن.', en: 'Let him drink coffee and improve.', arZ: 'Khallih yishrab ahwe w byit7assan.', next: 'h4r' },
      ],
    },
    h4r: {
      id: 'h4r',
      speaker: 'Maya',
      ar: 'قهوة؟ لا... مع الدوخة ممكن تزيد الوضع.',
      en: 'Coffee? no... with dizziness it can worsen.',
      arZ: 'Ahwe? la... ma3 el-dawkha momkin تزيد el-waD3.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'h4r_rep', ar: 'صح، آسف. مي وهواء أحسن.', en: 'Right, sorry. Water and air are better.', arZ: 'Sa7, asef. May w hawa a7san.', next: 'h5' },
        { id: 'h4r_neu', ar: 'تمام، بنتبع التعليمات.', en: 'Okay, we follow instructions.', arZ: 'Tamaam, بنتبع el-ta3leemat.', next: 'h5' },
      ],
    },
    h5: {
      id: 'h5',
      speaker: 'Maya',
      ar: 'في شغلة صغيرة: بتتصل بالإسعاف إذا ساءت حالته؟',
      en: 'Small thing: can you call ambulance if he worsens?',
      arZ: 'Fi shaghleh zghireh: btettesel bel-is3af iza sa2at 7alto?',
      state: 'neutral',
      tension: 3,
      choices: [
        { id: 'h5_sup', ar: 'أكيد، الرقم جاهز عندي.', en: 'Sure, number is ready with me.', arZ: 'Akeed, el-raqam جاهز 3ندي.', next: 'h6' },
        { id: 'h5_neu', ar: 'تمام، بعطيهم التفاصيل إذا لزم.', en: 'Okay, I give details if needed.', arZ: 'Tamaam, ba3Teehom el-tafaseel iza lazem.', next: 'h6' },
        { id: 'h5_trap', ar: 'مش ضروري نكبر الموضوع.', en: 'No need to exaggerate this.', arZ: 'Mish Daroori nkabber el-mawdoo3.', next: 'h5r' },
      ],
    },
    h5r: {
      id: 'h5r',
      speaker: 'Maya',
      ar: 'أنا مش مكبرة... أنا بحمي الفريق.',
      en: 'I am not exaggerating... I am protecting team.',
      arZ: 'Ana mish مكبرة... ana ba7mi el-faree2.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'h5r_rep', ar: 'معك حق. بنمشي على الأمان أول.', en: 'You are right. Safety comes first.', arZ: 'Ma3ik 7a2. Bnimshi 3al-aman awwal.', next: 'h6' },
        { id: 'h5r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 'h_end_awk' },
      ],
    },
    h6: {
      id: 'h6',
      speaker: 'Maya',
      ar: 'منيح... سامر هدي شوي. النفس صار أبطأ.',
      en: 'Good... Samer calmed down. Breathing is slower now.',
      arZ: 'Mnee7... Samer hadi shway. El-nafas Sar abTa2 el-aan.',
      state: 'relaxed',
      tension: 2,
      choices: [
        { id: 'h6_sup', ar: 'الحمد لله. نخليه يرتاح ونراقبه.', en: 'Great. Let him rest and monitor him.', arZ: 'El7amdulillah. Nkhallih yirta7 w nra2bo.', next: 'h7' },
        { id: 'h6_neu', ar: 'تمام، بنكتب تقرير حادث مختصر.', en: 'Okay, write short incident report.', arZ: 'Tamaam, bnoktob taqreer 7adeth mukhtaSar.', next: 'h7' },
        { id: 'h6_trap', ar: 'خلص، كان توتر عالفاضي.', en: 'Done, it was useless stress.', arZ: 'Khalas, kan tawattor 3al-faDi.', next: 'h6r' },
      ],
    },
    h6r: {
      id: 'h6r',
      speaker: 'Maya',
      ar: 'يعني... الاحتياط مش فاضي. أنقذ موقف.',
      en: 'I mean... precautions are not useless. They save situations.',
      arZ: 'Ya3ni... el-e7tiyaT mish faDi. InqaZ mawqef.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 'h6r_rep', ar: 'صح، يعطيكي العافية على التصرف.', en: 'Right, thanks for handling this.', arZ: 'Sa7, ya3teeki el-3afyeh 3al-taSarruf.', next: 'h7' },
        { id: 'h6r_neu', ar: 'تمام، نكمل التحديث.', en: 'Okay, continue plan update.', arZ: 'Tamaam, nkammel el-ta7deeth.', next: 'h_end_neu' },
      ],
    },
    h7: {
      id: 'h7',
      speaker: 'Maya',
      ar: 'خلصنا التحديث. اليوم تعلمنا درس مهم.',
      en: 'Update done. Today we learned important lesson.',
      arZ: 'Khalasna el-ta7deeth. El-yom ta3allamna dars mohem.',
      state: 'warm',
      tension: 2,
      choices: [
        { id: 'h7_warm', ar: 'أكيد. سلامة الفريق قبل كل شي.', en: 'Sure. Team safety comes first.', arZ: 'Akeed. Salamet el-faree2 qabl kol shi.', next: 'h_end_warm' },
        { id: 'h7_neu', ar: 'تمام، بنرسل النسخة النهائية.', en: 'Okay, we send final version.', arZ: 'Tamaam, bnersel el-nuskha el-niha2iyyeh.', next: 'h_end_neu' },
        { id: 'h7_trap', ar: 'الموضوع أخذ وقت زيادة.', en: 'This took too much time.', arZ: 'El-mawdoo3 akhad wa2et ziyadeh.', next: 'h_end_neu' },
      ],
    },
    h_end_warm: {
      id: 'h_end_warm',
      speaker: 'Maya',
      ar: 'يسلمو يا أحمد. وجودك ريّح الفريق.',
      en: 'Thanks Ahmed. Your presence reassured team.',
      arZ: 'Yislamo ya Ahmed. Wojoodak rayya7 el-faree2.',
      state: 'warm',
      tension: 1,
      choices: [{ id: 'h_end_warm_c', ar: 'ولا يهمك، إحنا فريق واحد.', en: 'Anytime, we are one team.', arZ: 'Wala yhemmik, e7na faree2 wa7ad.', next: 'END' }],
    },
    h_end_neu: {
      id: 'h_end_neu',
      speaker: 'Maya',
      ar: 'تمام، نرجع لمهامنا بهدوء.',
      en: 'Okay, let us return to tasks calmly.',
      arZ: 'Tamaam, narja3 le-mhamna b-hodoo2.',
      state: 'neutral',
      tension: 2,
      choices: [{ id: 'h_end_neu_c', ar: 'يلا.', en: 'Let us go.', arZ: 'Yalla.', next: 'END' }],
    },
    h_end_awk: {
      id: 'h_end_awk',
      speaker: 'Maya',
      ar: 'طيب... كل واحد يتصرف لحاله.',
      en: 'Okay... everyone handles things alone.',
      arZ: 'Tayyeb... kol wa7ad yetsaRraf la7alo.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'h_end_awk_fix', ar: 'استني، آسف. خلينا نكمل مع بعض.', en: 'Wait, sorry. Let us continue together.', arZ: 'Istanni, asef. Khallina nkammel ma3 ba3D.', next: 'h_end_neu' },
        { id: 'h_end_awk_keep', ar: 'تمام.', en: 'Fine.', arZ: 'Tamaam.', next: 'END' },
      ],
    },
    END: {
      id: 'END',
      speaker: 'System',
      ar: '✅ نهاية المشهد.',
      en: '✅ End of scene.',
      arZ: '✅ Nehayet el-mashhad.',
      state: 'neutral',
      tension: 1,
      choices: [],
    },
  },
};
