import { LESSON_ID_SHOPPING } from '../../core/constants.js';

export const dialogueId = 'BD::' + LESSON_ID_SHOPPING;

export const dialogue = {
  meta: {
    level: 'Pre-Intermediate',
    unit: 'Shopping & Prices',
    title: 'Shopping & Prices - Vendor Decisions',
    emotionalTracking: true,
    tensionCurve: true,
    trapLayering: true,
    setting: 'Workplace',
  },
  startNodeId: 's1',
  nodes: {
    s1: {
      id: 's1',
      speaker: 'Rana',
      ar: 'صباح الخير أحمد. بدنا نشتري مستلزمات المكتب.',
      en: 'Good morning Ahmed. We need to buy office supplies.',
      arZ: 'Saba7 el-kheir Ahmed. Badna نشتري mustalzamat el-maktab.',
      state: 'neutral',
      tension: 1,
      choices: [
        { id: 's1_sup', ar: 'صباح النور. ممتاز، نبدأ بالمقارنة.', en: 'Morning. Great, let us compare first.', arZ: 'Saba7 el-noor. Momtaz, nabda bel-moqaraneh.', next: 's2' },
        { id: 's1_neu', ar: 'صباح النور. شو القائمة؟', en: 'Morning. What is the list?', arZ: 'Saba7 el-noor. Sho el-qa2meh?', next: 's2b' },
        { id: 's1_trap', ar: 'ليش ما نشتري من أي محل؟', en: 'Why not buy from any shop?', arZ: 'Leish ma nishtiri men ay ma7al?', next: 's2c' },
      ],
    },
    s2: {
      id: 's2',
      speaker: 'Rana',
      ar: 'آه... أنا متوترة من ميزانية الشهر.',
      en: 'Ah... I am stressed about this month budget.',
      arZ: 'Ah... ana mtawattreh men meezaniyet el-shahr.',
      state: 'stressed',
      tension: 2,
      choices: [
        { id: 's2_sup', ar: 'ولا يهمك. بنمسك الأرخص والجودة المقبولة.', en: 'No worries. We choose cheapest with acceptable quality.', arZ: 'Wala yhemmik. Bnimsik el-arkhaS wel-jawdeh el-maqbooleh.', next: 's3' },
        { id: 's2_neu', ar: 'تمام، نحدد سقف لكل بند.', en: 'Okay, set cap for each item.', arZ: 'Tamaam, n7added saqf le-kol band.', next: 's3' },
        { id: 's2_trap', ar: 'الميزانية دايماً شماعة.', en: 'Budget is always an excuse.', arZ: 'El-meezaniyyeh dayman shamma3a.', next: 's2r' },
      ],
    },
    s2b: {
      id: 's2b',
      speaker: 'Rana',
      ar: 'على فكرة، بدنا ورق، حبر، وسماعات للاجتماعات.',
      en: 'By the way, we need paper, ink, and headsets.',
      arZ: '3ala fekra, badna wara2, 7ibr, w سماعات lel-ijtima3at.',
      state: 'neutral',
      tension: 2,
      choices: [
        { id: 's2b_sup', ar: 'منيح. بنرتب حسب الأولوية.', en: 'Good. We order by priority.', arZ: 'Mnee7. Bnratteb 7asab el-awlawiyyeh.', next: 's3' },
        { id: 's2b_neu', ar: 'تمام، خلينا نقارن ثلاث عروض.', en: 'Okay, let us compare three offers.', arZ: 'Tamaam, khallina n2aren thalath 3orood.', next: 's3' },
        { id: 's2b_trap', ar: 'سماعات؟ مش ضرورية.', en: 'Headsets? not necessary.', arZ: 'Sama3at? mish Darooriyyeh.', next: 's2r' },
      ],
    },
    s2c: {
      id: 's2c',
      speaker: 'Rana',
      ar: 'يعني... في فروقات سعر كبيرة جداً.',
      en: 'I mean... there are very big price differences.',
      arZ: 'Ya3ni... fi فروقات se3er kbeereh jiddan.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 's2c_rep', ar: 'معك حق. خلينا نختار بعقل.', en: 'You are right. Let us choose wisely.', arZ: 'Ma3ik 7a2. Khallina nkhtar b-3aql.', next: 's3' },
        { id: 's2c_neu', ar: 'تمام، ورجيني الأسعار.', en: 'Okay, show me prices.', arZ: 'Tamaam, warjeeni el-as3ar.', next: 's3' },
      ],
    },
    s2r: {
      id: 's2r',
      speaker: 'Rana',
      ar: 'طيب... إذا غلطنا، المشتريات كلها بتخرب.',
      en: 'Okay... if we choose wrong, all purchasing fails.',
      arZ: 'Tayyeb... iza ghliTna, el-mushtaryat كلها btikhreb.',
      state: 'stressed',
      tension: 4,
      choices: [
        { id: 's2r_rep', ar: 'صح. نقرر على بيانات مش مزاج.', en: 'Right. We decide by data not mood.', arZ: 'Sa7. Nqarrer 3ala bayanat mish mizaj.', next: 's3' },
        { id: 's2r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 's_end_awk' },
      ],
    },
    s3: {
      id: 's3',
      speaker: 'Nabil',
      ar: 'مقاطعة: المورد رفع سعر الحبر هالصبح.',
      en: 'Interruption: vendor increased ink price this morning.',
      arZ: 'Moqata3a: el-mowarred rafa3 se3er el-7ibr hal-sob7.',
      state: 'stressed',
      tension: 3,
      choices: [
        { id: 's3_sup', ar: 'تمام، بنتفاوض معه فوراً.', en: 'Okay, we negotiate with him now.', arZ: 'Tamaam, بنتفاوض ma3o فوراً.', next: 's4' },
        { id: 's3_neu', ar: 'منيح، نطلب عرض مكتوب جديد.', en: 'Good, request a new written quote.', arZ: 'Mnee7, netlob 3arD maktoob jdeed.', next: 's4' },
        { id: 's3_trap', ar: 'أكيد عم يستغلنا.', en: 'Sure he is exploiting us.', arZ: 'Akeed 3am yestaghillna.', next: 's3r' },
      ],
    },
    s3r: {
      id: 's3r',
      speaker: 'Rana',
      ar: 'استنى... ممكن في سبب بالسوق.',
      en: 'Wait... maybe there is a market reason.',
      arZ: 'Istanna... momkin fi sabab bel-sooq.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 's3r_rep', ar: 'صح. خلينا نسأل قبل الحكم.', en: 'Right. Let us ask before judging.', arZ: 'Sa7. Khallina نسأل qabl el-7okm.', next: 's4' },
        { id: 's3r_neu', ar: 'تمام، نطلب توضيح رسمي.', en: 'Okay, request formal clarification.', arZ: 'Tamaam, netlob tawDee7 رسمي.', next: 's4' },
      ],
    },
    s4: {
      id: 's4',
      speaker: 'Rana',
      ar: 'في شغلة صغيرة: بتتصل بالمورد وتفاوضه؟',
      en: 'Small request: can you call vendor and negotiate?',
      arZ: 'Fi shaghleh zghireh: btettesel bel-mowarred w tfawDo?',
      state: 'neutral',
      tension: 3,
      choices: [
        { id: 's4_sup', ar: 'أكيد. بعرض عليه طلب سنوي.', en: 'Sure. I offer him annual order.', arZ: 'Akeed. Ba3raD 3aleh talab sanawi.', next: 's5' },
        { id: 's4_neu', ar: 'بعد دقيقة باتصل.', en: 'I call in a minute.', arZ: 'Ba3d da2ee2a باتصل.', next: 's5b' },
        { id: 's4_trap', ar: 'التفاوض مش شغلتي.', en: 'Negotiation is not my job.', arZ: 'El-tafawoD mish shoghlti.', next: 's4r' },
      ],
    },
    s4r: {
      id: 's4r',
      speaker: 'Rana',
      ar: 'أنا بس بحتاج دعمك بهالمكالمة.',
      en: 'I only need your support in this call.',
      arZ: 'Ana bas ba7taj da3mak b-hal-mokalmé.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 's4r_rep', ar: 'معك حق. أنا باتصل هلق.', en: 'You are right. I call now.', arZ: 'Ma3ik 7a2. Ana باتصل halla2.', next: 's5' },
        { id: 's4r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 's_end_awk' },
      ],
    },
    s5: {
      id: 's5',
      speaker: 'Rana',
      ar: 'ممتاز! وافق على خصم عشرة بالمية.',
      en: 'Great! he accepted a ten percent discount.',
      arZ: 'Momtaz! وافق 3ala khaSm 3ashra bel-miyyeh.',
      state: 'relaxed',
      tension: 2,
      choices: [
        { id: 's5_sup', ar: 'حلو كتير. هيك وفرنا مبلغ محترم.', en: 'Very good. This saved a decent amount.', arZ: '7elw kteer. Heik waffarna mablagh mo7taram.', next: 's6' },
        { id: 's5_neu', ar: 'تمام، نثبت الطلب الآن.', en: 'Okay, confirm order now.', arZ: 'Tamaam, nthabbit el-talab el-aan.', next: 's6' },
        { id: 's5_trap', ar: 'كان لازم أكثر من هيك.', en: 'It should have been more discount.', arZ: 'Kan lazem akthar men heik.', next: 's5r' },
      ],
    },
    s5b: {
      id: 's5b',
      speaker: 'Rana',
      ar: 'أوكي... بس إذا تأخرنا بنخسر العرض.',
      en: 'Okay... but if we delay we lose quote.',
      arZ: 'Okay... bas iza ta2akharna bnkhasar el-3arD.',
      state: 'tired',
      tension: 3,
      choices: [
        { id: 's5b_sup', ar: 'خلص، حكيت معه وخفض السعر.', en: 'Done, I called and he reduced price.', arZ: 'Khalas, 7akeit ma3o w khaffaD el-se3er.', next: 's6' },
        { id: 's5b_neu', ar: 'تمام، نرسل أمر الشراء.', en: 'Okay, we send purchase order.', arZ: 'Tamaam, nersel amr el-shira2.', next: 's6' },
        { id: 's5b_trap', ar: 'إذا راح العرض مش مشكلتي.', en: 'If quote is gone, not my issue.', arZ: 'Iza ra7 el-3arD mish mushkilti.', next: 's_end_awk' },
      ],
    },
    s5r: {
      id: 's5r',
      speaker: 'Rana',
      ar: 'هههه... خلينا نفرح باللي جبناه اليوم.',
      en: 'Haha... let us be happy with what we got today.',
      arZ: 'Hahaha... khallina nifra7 belli jibnah el-yom.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 's5r_rep', ar: 'صح، شغل ممتاز منك.', en: 'Right, excellent work from you.', arZ: 'Sa7, shoghl momtaz منك.', next: 's6' },
        { id: 's5r_neu', ar: 'تمام، نكمل الإجراءات.', en: 'Okay, continue procedures.', arZ: 'Tamaam, nkammel el-ijra2at.', next: 's_end_neu' },
      ],
    },
    s6: {
      id: 's6',
      speaker: 'Rana',
      ar: 'انتهينا. اليوم الشراء كان ذكي ومنظم.',
      en: 'Done. Today purchasing was smart and organized.',
      arZ: 'Inteheina. El-yom el-shira2 kan zaki w munaZZam.',
      state: 'warm',
      tension: 2,
      choices: [
        { id: 's6_warm', ar: 'يسعدك. الأسبوع الجاي بنفاوض أفضل.', en: 'Great. Next week we negotiate better.', arZ: 'Yis3dik. El-osboo3 el-jay bnfawweD afDal.', next: 's_end_warm' },
        { id: 's6_neu', ar: 'تمام، نرفع التقرير للإدارة.', en: 'Okay, raise report to management.', arZ: 'Tamaam, narfa3 el-taqreer lel-idara.', next: 's_end_neu' },
        { id: 's6_trap', ar: 'المهم خلصنا.', en: 'Important thing is we are done.', arZ: 'El-mohem khalasna.', next: 's_end_neu' },
      ],
    },
    s_end_warm: {
      id: 's_end_warm',
      speaker: 'Rana',
      ar: 'اتفقنا. القهوة عليّ اليوم.',
      en: 'Deal. Coffee on me today.',
      arZ: 'Ittafaqna. El-ahwe 3alay el-yom.',
      state: 'warm',
      tension: 1,
      choices: [{ id: 's_end_warm_c', ar: 'تم.', en: 'Done.', arZ: 'Tam.', next: 'END' }],
    },
    s_end_neu: {
      id: 's_end_neu',
      speaker: 'Rana',
      ar: 'تمام، ننتقل للمهمة الجاية.',
      en: 'Okay, we move to next task.',
      arZ: 'Tamaam, nنتقل lel-mihmeh el-jayeh.',
      state: 'neutral',
      tension: 2,
      choices: [{ id: 's_end_neu_c', ar: 'يلا.', en: 'Let us go.', arZ: 'Yalla.', next: 'END' }],
    },
    s_end_awk: {
      id: 's_end_awk',
      speaker: 'Rana',
      ar: 'طيب... أنا بكمل المشتريات لحالي.',
      en: 'Okay... I finish purchasing alone.',
      arZ: 'Tayyeb... ana بكمل el-mushtaryat la7ali.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 's_end_awk_fix', ar: 'استني، آسف. خلينا نكمل سوا.', en: 'Wait, sorry. Let us finish together.', arZ: 'Istanni, asef. Khallina nkammel sawa.', next: 's_end_neu' },
        { id: 's_end_awk_keep', ar: 'تمام.', en: 'Fine.', arZ: 'Tamaam.', next: 'END' },
      ],
    },
    END: {
      id: 'END',
      speaker: 'System',
      ar: '✅ نهاية المشهد.',
      en: '✅ End of scene.',
      arZ: '✅ Nehayet el-mashhad.',
      state: 'neutral',
      tension: 1,
      choices: [],
    },
  },
};
