import { LESSON_ID_WEATHER } from '../../core/constants.js';

export const dialogueId = 'BD::' + LESSON_ID_WEATHER;

export const dialogue = {
  meta: {
    level: 'Pre-Intermediate',
    unit: 'Weather & Small Talk',
    title: 'Weather & Small Talk - Visit Planning Decisions',
    emotionalTracking: true,
    tensionCurve: true,
    trapLayering: true,
    setting: 'Workplace',
  },
  startNodeId: 'w1',
  nodes: {
    w1: {
      id: 'w1',
      speaker: 'Dana',
      ar: 'صباح الخير أحمد. الجو اليوم غريب، صح؟',
      en: 'Good morning Ahmed. Weather is strange today, right?',
      arZ: 'Saba7 el-kheir Ahmed. El-jaw el-yom ghareeb, sa7?',
      state: 'neutral',
      tension: 1,
      choices: [
        { id: 'w1_sup', ar: 'صباح النور. آه، مطر وهوا قوي.', en: 'Morning. Yes, rain and strong wind.', arZ: 'Saba7 el-noor. Ah, maTar w hawa qawi.', next: 'w2' },
        { id: 'w1_neu', ar: 'صباح النور. كيف التوقع لبعد الظهر؟', en: 'Morning. What is forecast for afternoon?', arZ: 'Saba7 el-noor. Keef el-tawaqqo3 le-ba3d el-Duhr?', next: 'w2b' },
        { id: 'w1_trap', ar: 'جو عادي، ليش مكبرينها؟', en: 'Normal weather, why exaggerating?', arZ: 'Jaw 3adi, leish mkabbreenha?', next: 'w2c' },
      ],
    },
    w2: {
      id: 'w2',
      speaker: 'Dana',
      ar: 'آه... أنا متوترة، عندنا زيارة ميدانية.',
      en: 'Ah... I am stressed, we have a field visit.',
      arZ: 'Ah... ana mtawattreh, 3inna ziyara meydaniyyeh.',
      state: 'stressed',
      tension: 2,
      choices: [
        { id: 'w2_sup', ar: 'ولا يهمك. بنحضر خطة بديلة.', en: 'No worries. We prepare alternative plan.', arZ: 'Wala yhemmik. Bn7aDDer khittah badeeleh.', next: 'w3' },
        { id: 'w2_neu', ar: 'تمام، نراجع الطريق والزمن.', en: 'Okay, review route and timing.', arZ: 'Tamaam, nraje3 el-Taree2 wel-zaman.', next: 'w3' },
        { id: 'w2_trap', ar: 'الطقس مش عذر للتأجيل.', en: 'Weather is not excuse to postpone.', arZ: 'El-Taqs mish 3ozr lel-ta2jeel.', next: 'w2r' },
      ],
    },
    w2b: {
      id: 'w2b',
      speaker: 'Dana',
      ar: 'بالمناسبة، في احتمال عاصفة بعد ساعتين.',
      en: 'By the way, there is chance of storm in two hours.',
      arZ: 'Belmonasabe, fi i7timal 3aSfeh ba3d sa3tein.',
      state: 'neutral',
      tension: 2,
      choices: [
        { id: 'w2b_sup', ar: 'ممتاز إننا عرفنا بدري.', en: 'Great we knew early.', arZ: 'Momtaz ennna 3erefna badri.', next: 'w3' },
        { id: 'w2b_neu', ar: 'تمام، نضبط مواعيدنا.', en: 'Okay, we adjust our times.', arZ: 'Tamaam, nzabbet mawa3eedna.', next: 'w3' },
        { id: 'w2b_trap', ar: 'التوقعات غالباً غلط.', en: 'Forecasts are often wrong.', arZ: 'El-tawaqqo3at ghaleban ghalat.', next: 'w2r' },
      ],
    },
    w2c: {
      id: 'w2c',
      speaker: 'Dana',
      ar: 'يعني... مبارح نفس الجو وعطلنا الطريق.',
      en: 'I mean... yesterday same weather blocked road.',
      arZ: 'Ya3ni... mbar7 nafs el-jaw w 3aTTalna el-Taree2.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 'w2c_rep', ar: 'معك حق، آسف. خلينا نتصرف بحذر.', en: 'You are right, sorry. Let us act carefully.', arZ: 'Ma3ik 7a2, asef. Khallina netsaRraf b-7azar.', next: 'w3' },
        { id: 'w2c_neu', ar: 'تمام، شو الخطة؟', en: 'Okay, what is the plan?', arZ: 'Tamaam, sho el-khittah?', next: 'w3' },
      ],
    },
    w2r: {
      id: 'w2r',
      speaker: 'Dana',
      ar: 'طيب... تجاهل الطقس ممكن يعمل مشكلة كبيرة.',
      en: 'Okay... ignoring weather can make big problem.',
      arZ: 'Tayyeb... تجاهل el-Taqs momkin ya3mel mushkileh kbeereh.',
      state: 'stressed',
      tension: 4,
      choices: [
        { id: 'w2r_rep', ar: 'صح. السلامة أهم من العناد.', en: 'Right. Safety is more important than stubbornness.', arZ: 'Sa7. El-salameh ahamm men el-3inad.', next: 'w3' },
        { id: 'w2r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 'w_end_awk' },
      ],
    },
    w3: {
      id: 'w3',
      speaker: 'Basel',
      ar: 'مقاطعة: السائق حكى الطريق الساحلي مسكر.',
      en: 'Interruption: driver said coastal road is closed.',
      arZ: 'Moqata3a: el-sayye2 7aka el-Taree2 el-sa7li msakkar.',
      state: 'stressed',
      tension: 3,
      choices: [
        { id: 'w3_sup', ar: 'تمام، بنختار الطريق الداخلي فوراً.', en: 'Okay, choose inner road immediately.', arZ: 'Tamaam, bniktar el-Taree2 el-dakhli فوراً.', next: 'w4' },
        { id: 'w3_neu', ar: 'منيح، نعيد جدولة الزيارة.', en: 'Good, reschedule the visit.', arZ: 'Mnee7, n3eed jadwalet el-ziyara.', next: 'w4' },
        { id: 'w3_trap', ar: 'خليه يجرب، يمكن بيمشي.', en: 'Let him try, maybe it works.', arZ: 'Khallih yjarrib, yumkin byemshi.', next: 'w3r' },
      ],
    },
    w3r: {
      id: 'w3r',
      speaker: 'Dana',
      ar: 'استنى شوي... المغامرة هون مش ذكية.',
      en: 'Wait a bit... taking risk here is not smart.',
      arZ: 'Istanna shway... el-moghamarah hon mish zakiyyeh.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'w3r_rep', ar: 'معك حق. نلتزم بالطريق الآمن.', en: 'You are right. We follow safe road.', arZ: 'Ma3ik 7a2. Nلتزم bel-Taree2 el-amen.', next: 'w4' },
        { id: 'w3r_neu', ar: 'تمام، شو وقت الوصول المتوقع؟', en: 'Okay, expected arrival time?', arZ: 'Tamaam, sho wa2et el-wosool el-mutawaqqa3?', next: 'w4' },
      ],
    },
    w4: {
      id: 'w4',
      speaker: 'Dana',
      ar: 'في شغلة صغيرة: بتبعت تحديث للعميل؟',
      en: 'Small request: can you send update to client?',
      arZ: 'Fi shaghleh zghireh: btib3at ta7deeth lel-3ameel?',
      state: 'neutral',
      tension: 3,
      choices: [
        { id: 'w4_sup', ar: 'أكيد. بكتب: الوصول متأخر عشر دقايق.', en: 'Sure. I write: arrival delayed ten minutes.', arZ: 'Akeed. Bktob: el-wosool mota2akher 3ashr da2aye2.', next: 'w5' },
        { id: 'w4_neu', ar: 'بعد دقيقة ببعت الرسالة.', en: 'In one minute I send message.', arZ: 'Ba3d da2ee2a bab3at el-risaleh.', next: 'w5b' },
        { id: 'w4_trap', ar: 'إنتِ ابعتي، أنا مش فاضي.', en: 'You send it, I am busy.', arZ: 'Enti eb3ati, ana mish fadi.', next: 'w4r' },
      ],
    },
    w4r: {
      id: 'w4r',
      speaker: 'Dana',
      ar: 'أنا عم أرتب السائق... بحتاج مساعدتك.',
      en: 'I am arranging driver... I need your help.',
      arZ: 'Ana 3am aratteb el-sayye2... ba7taj msa3adtak.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'w4r_rep', ar: 'معك حق. أنا ببعت التحديث هلق.', en: 'You are right. I send update now.', arZ: 'Ma3ik 7a2. Ana bab3at el-ta7deeth halla2.', next: 'w5' },
        { id: 'w4r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 'w_end_awk' },
      ],
    },
    w5: {
      id: 'w5',
      speaker: 'Dana',
      ar: 'ممتاز. العميل تفهّم الوضع وشكرنا.',
      en: 'Excellent. Client understood and thanked us.',
      arZ: 'Momtaz. El-3ameel tafahham el-waD3 w shakarna.',
      state: 'relaxed',
      tension: 2,
      choices: [
        { id: 'w5_sup', ar: 'حلو. التواصل الواضح دايماً بينجح.', en: 'Nice. Clear communication always succeeds.', arZ: '7elw. El-tawaSol el-waDe7 dayman byinja7.', next: 'w6' },
        { id: 'w5_neu', ar: 'تمام، ننطلق الآن.', en: 'Okay, we move now.', arZ: 'Tamaam, ننطلق el-aan.', next: 'w6' },
        { id: 'w5_trap', ar: 'كان رح يتفهم بدون رسالة.', en: 'He would understand without message.', arZ: 'Kan ra7 yitfahham bdoon risaleh.', next: 'w5r' },
      ],
    },
    w5b: {
      id: 'w5b',
      speaker: 'Dana',
      ar: 'أوكي... بس الوقت عم يضغطنا.',
      en: 'Okay... but time is pressuring us.',
      arZ: 'Okay... bas el-wa2et 3am yDa8Tna.',
      state: 'tired',
      tension: 3,
      choices: [
        { id: 'w5b_sup', ar: 'خلص، الرسالة انبعتت.', en: 'Done, message was sent.', arZ: 'Khalas, el-risaleh inba3atet.', next: 'w6' },
        { id: 'w5b_neu', ar: 'تمام، نمشي.', en: 'Okay, let us go.', arZ: 'Tamaam, nimshi.', next: 'w6' },
        { id: 'w5b_trap', ar: 'إذا تأخرنا مش مسؤوليتي.', en: 'If delayed, not my responsibility.', arZ: 'Iza ta2akharna mish mas2ooliyti.', next: 'w_end_awk' },
      ],
    },
    w5r: {
      id: 'w5r',
      speaker: 'Dana',
      ar: 'هههه... الرسالة بتحفظ شكلنا المهني.',
      en: 'Haha... message preserves our professional image.',
      arZ: 'Hahaha... el-risaleh bt7faZ shaklna el-mehni.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 'w5r_rep', ar: 'صح، نقطة مهمة.', en: 'Right, important point.', arZ: 'Sa7, no2Ta mohemmeh.', next: 'w6' },
        { id: 'w5r_neu', ar: 'تمام، نكمل.', en: 'Okay, continue.', arZ: 'Tamaam, nkammel.', next: 'w_end_neu' },
      ],
    },
    w6: {
      id: 'w6',
      speaker: 'Dana',
      ar: 'رغم الجو، الخطة مشيت ممتاز اليوم.',
      en: 'Despite weather, plan worked excellent today.',
      arZ: 'Ra8m el-jaw, el-khittah mishyet momtaz el-yom.',
      state: 'warm',
      tension: 2,
      choices: [
        { id: 'w6_warm', ar: 'يسعدك. التنسيق أنقذ الموقف.', en: 'Great. Coordination saved situation.', arZ: 'Yis3dik. El-tanseeq anqaZ el-mawqef.', next: 'w_end_warm' },
        { id: 'w6_neu', ar: 'تمام، نثبت الملاحظات لمرات الجاية.', en: 'Okay, we document notes for next times.', arZ: 'Tamaam, nthabbit el-mola7azat lel-marrrat el-jayeh.', next: 'w_end_neu' },
        { id: 'w6_trap', ar: 'المهم خلصنا وخلاص.', en: 'Important is we are done.', arZ: 'El-mohem khalasna w khalas.', next: 'w_end_neu' },
      ],
    },
    w_end_warm: {
      id: 'w_end_warm',
      speaker: 'Dana',
      ar: 'متفقين. بعد الدوام قهوة دافية؟',
      en: 'Agreed. Warm coffee after work?',
      arZ: 'Mottafgeen. Ba3d el-dawam ahwe dafyeh?',
      state: 'warm',
      tension: 1,
      choices: [{ id: 'w_end_warm_c', ar: 'أكيد.', en: 'Sure.', arZ: 'Akeed.', next: 'END' }],
    },
    w_end_neu: {
      id: 'w_end_neu',
      speaker: 'Dana',
      ar: 'تمام، كل واحد على مهمته.',
      en: 'Okay, each one to their task.',
      arZ: 'Tamaam, kol wa7ad 3ala mihmto.',
      state: 'neutral',
      tension: 2,
      choices: [{ id: 'w_end_neu_c', ar: 'يلا.', en: 'Let us go.', arZ: 'Yalla.', next: 'END' }],
    },
    w_end_awk: {
      id: 'w_end_awk',
      speaker: 'Dana',
      ar: 'طيب... كل واحد يدبر حاله.',
      en: 'Okay... everyone handles themselves.',
      arZ: 'Tayyeb... kol wa7ad ydabber 7alo.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'w_end_awk_fix', ar: 'استني، آسف. نكمل مع بعض.', en: 'Wait, sorry. Let us continue together.', arZ: 'Istanni, asef. Nkammel ma3 ba3D.', next: 'w_end_neu' },
        { id: 'w_end_awk_keep', ar: 'تمام.', en: 'Fine.', arZ: 'Tamaam.', next: 'END' },
      ],
    },
    END: {
      id: 'END',
      speaker: 'System',
      ar: '✅ نهاية المشهد.',
      en: '✅ End of scene.',
      arZ: '✅ Nehayet el-mashhad.',
      state: 'neutral',
      tension: 1,
      choices: [],
    },
  },
};
