import { LESSON_ID_WORK_STUDY } from '../../core/constants.js';

export const dialogueId = 'BD::' + LESSON_ID_WORK_STUDY;

export const dialogue = {
  meta: {
    level: 'Pre-Intermediate',
    unit: 'Work & Study',
    title: 'Work & Study - Deadline Decisions',
    emotionalTracking: true,
    tensionCurve: true,
    trapLayering: true,
    setting: 'Workplace',
  },
  startNodeId: 'ws1',
  nodes: {
    ws1: {
      id: 'ws1',
      speaker: 'Haneen',
      ar: 'صباح الخير أحمد. جاهز لاجتماع المشروع؟',
      en: 'Good morning Ahmed. Ready for project meeting?',
      arZ: 'Saba7 el-kheir Ahmed. Jahiz le-ijtima3 el-mashroo3?',
      state: 'neutral',
      tension: 1,
      choices: [
        { id: 'ws1_sup', ar: 'صباح النور. جاهز، خلينا نبدأ.', en: 'Morning. Ready, let us start.', arZ: 'Saba7 el-noor. Jahiz, khallina nabda.', next: 'ws2' },
        { id: 'ws1_neu', ar: 'صباح النور. شو أول ملف؟', en: 'Morning. What is first file?', arZ: 'Saba7 el-noor. Sho awwal malaf?', next: 'ws2b' },
        { id: 'ws1_trap', ar: 'لسا بدري عالاجتماع.', en: 'It is still early for meeting.', arZ: 'Lissa badri 3al-ijtima3.', next: 'ws2c' },
      ],
    },
    ws2: {
      id: 'ws2',
      speaker: 'Haneen',
      ar: 'آه... أنا مرهقة شوي من دراسة مبارح.',
      en: 'Ah... I am a bit exhausted from studying yesterday.',
      arZ: 'Ah... ana marha2a shway men deraset mbar7.',
      state: 'tired',
      tension: 2,
      choices: [
        { id: 'ws2_sup', ar: 'سلامتك. بقدر أغطي جزء العرض.', en: 'Hope you are well. I can cover part of presentation.', arZ: 'Salamtik. Bqdar aghaTTi juz2 el-3arD.', next: 'ws3' },
        { id: 'ws2_neu', ar: 'تمام، نوزع المهام بوضوح.', en: 'Okay, we split tasks clearly.', arZ: 'Tamaam, nwazza3 el-mham b-wuDoo7.', next: 'ws3' },
        { id: 'ws2_trap', ar: 'كلنا مرهقين أصلاً.', en: 'We are all exhausted anyway.', arZ: 'Kollna marha2een aslan.', next: 'ws2r' },
      ],
    },
    ws2b: {
      id: 'ws2b',
      speaker: 'Haneen',
      ar: 'قبل ما نكمل، بدنا نثبت خطة الأسبوع.',
      en: 'Before we continue, we must confirm weekly plan.',
      arZ: 'Qabel ma nkammel, badna nthabbit khittet el-osboo3.',
      state: 'neutral',
      tension: 2,
      choices: [
        { id: 'ws2b_sup', ar: 'ممتاز. أنا بكتب التوزيع الآن.', en: 'Great. I write the distribution now.', arZ: 'Momtaz. Ana bktob el-tawzee3 el-aan.', next: 'ws3' },
        { id: 'ws2b_neu', ar: 'تمام، مين مسؤول المتابعة؟', en: 'Okay, who handles follow-up?', arZ: 'Tamaam, meen mas2ool el-motaba3a?', next: 'ws3' },
        { id: 'ws2b_trap', ar: 'كل أسبوع نفس الكلام.', en: 'Every week same talk.', arZ: 'Kol osboo3 nafs el-kalam.', next: 'ws2r' },
      ],
    },
    ws2c: {
      id: 'ws2c',
      speaker: 'Haneen',
      ar: 'يعني... الموعد اتقدم، والعميل مستعجل.',
      en: 'I mean... time moved earlier and client is in hurry.',
      arZ: 'Ya3ni... el-maw3ed etqaddam, wel-3ameel mista3jel.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 'ws2c_rep', ar: 'معك حق، آسف. نبدأ مباشرة.', en: 'You are right, sorry. We start directly.', arZ: 'Ma3ik 7a2, asef. Nabda mobashara.', next: 'ws3' },
        { id: 'ws2c_neu', ar: 'تمام، شو المطلوب أول؟', en: 'Okay, what is first required?', arZ: 'Tamaam, sho el-matloub awwal?', next: 'ws3' },
      ],
    },
    ws2r: {
      id: 'ws2r',
      speaker: 'Haneen',
      ar: 'طيب... بس لازم نكسر هالدائرة اليوم.',
      en: 'Okay... but we need to break this cycle today.',
      arZ: 'Tayyeb... bas lazem nkسر hal-da2rah el-yom.',
      state: 'stressed',
      tension: 4,
      choices: [
        { id: 'ws2r_rep', ar: 'صح. خلينا نشتغل بطريقة أذكى.', en: 'Right. Let us work in smarter way.', arZ: 'Sa7. Khallina nishtighil b-Taree2a azka.', next: 'ws3' },
        { id: 'ws2r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 'ws_end_awk' },
      ],
    },
    ws3: {
      id: 'ws3',
      speaker: 'Yousef',
      ar: 'مقاطعة: اللابتوب ما عم يفتح ملف الشرائح.',
      en: 'Interruption: laptop is not opening slides file.',
      arZ: 'Moqata3a: el-laptop ma 3am yfta7 malaf el-shara2e7.',
      state: 'stressed',
      tension: 3,
      choices: [
        { id: 'ws3_sup', ar: 'أنا براجع النسخة الاحتياطية فوراً.', en: 'I check backup version right now.', arZ: 'Ana braje3 el-nuskha el-i7tiyaTiyyeh فوراً.', next: 'ws4' },
        { id: 'ws3_neu', ar: 'تمام، شغل النسخة على الدرايف.', en: 'Okay, run drive version.', arZ: 'Tamaam, shaghghil el-nuskha 3al-drive.', next: 'ws4' },
        { id: 'ws3_trap', ar: 'أكيد حدا خربط بالملفات.', en: 'Sure someone messed files.', arZ: 'Akeed 7ada kharbaT bel-malafat.', next: 'ws3r' },
      ],
    },
    ws3r: {
      id: 'ws3r',
      speaker: 'Haneen',
      ar: 'استنى... هاد وقت حل، مش وقت لوم.',
      en: 'Wait... this is time to solve, not blame.',
      arZ: 'Istanna... had wa2et 7all, mish wa2et lawm.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'ws3r_rep', ar: 'معك حق. خلينا نركز على الحل.', en: 'You are right. Let us focus on fix.', arZ: 'Ma3ik 7a2. Khallina narakkiz 3al-7all.', next: 'ws4' },
        { id: 'ws3r_neu', ar: 'تمام، شو البديل الأسرع؟', en: 'Okay, what is fastest alternative?', arZ: 'Tamaam, sho el-badeel el-asra3?', next: 'ws4' },
      ],
    },
    ws4: {
      id: 'ws4',
      speaker: 'Haneen',
      ar: 'في شغلة صغيرة: بتراجع سلايد الأرقام؟',
      en: 'Small request: can you review numbers slide?',
      arZ: 'Fi shaghleh zghireh: btraje3 slide el-arqam?',
      state: 'neutral',
      tension: 3,
      choices: [
        { id: 'ws4_sup', ar: 'أكيد. بعطيك ملاحظات دقيقة.', en: 'Sure. I give precise notes.', arZ: 'Akeed. Ba3Teeki mola7azat daqeeqa.', next: 'ws5' },
        { id: 'ws4_neu', ar: 'بعد دقيقة براجعه.', en: 'I review it in one minute.', arZ: 'Ba3d da2ee2a braje3o.', next: 'ws5b' },
        { id: 'ws4_trap', ar: 'مش فاضي لهالتفاصيل.', en: 'Not free for these details.', arZ: 'Mish fadi la-hal-tafaseel.', next: 'ws4r' },
      ],
    },
    ws4r: {
      id: 'ws4r',
      speaker: 'Haneen',
      ar: 'التفاصيل هي اللي بتنقذنا قدام العميل.',
      en: 'Details are what save us before client.',
      arZ: 'El-tafaseel hiyye elli btinqizna qoddam el-3ameel.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'ws4r_rep', ar: 'صح، آسف. براجعها حالاً.', en: 'Right, sorry. I review now.', arZ: 'Sa7, asef. Braje3ha 7alan.', next: 'ws5' },
        { id: 'ws4r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 'ws_end_awk' },
      ],
    },
    ws5: {
      id: 'ws5',
      speaker: 'Haneen',
      ar: 'ممتاز. السلايد واضح، والأرقام مضبوطة.',
      en: 'Excellent. Slide is clear and numbers are correct.',
      arZ: 'Momtaz. El-slide wade7, wel-arqam mazbooTa.',
      state: 'relaxed',
      tension: 2,
      choices: [
        { id: 'ws5_sup', ar: 'حلو. خلينا نتمرن دقيقتين قبل العرض.', en: 'Nice. Let us rehearse two minutes before presentation.', arZ: '7elw. Khallina nتمرن da2ee2tein qabl el-3arD.', next: 'ws6' },
        { id: 'ws5_neu', ar: 'تمام، بنبلش بالافتتاحية.', en: 'Okay, we start opening.', arZ: 'Tamaam, bnballesh bel-iftiTa7iyyeh.', next: 'ws6' },
        { id: 'ws5_trap', ar: 'الموضوع كان أبسط من كل هالتوتر.', en: 'This was simpler than all this stress.', arZ: 'El-mawdoo3 kan absaT men kol hal-tawattor.', next: 'ws5r' },
      ],
    },
    ws5b: {
      id: 'ws5b',
      speaker: 'Haneen',
      ar: 'أوكي... بس ضل خمس دقايق للاجتماع.',
      en: 'Okay... but only five minutes left.',
      arZ: 'Okay... bas Dall khams da2aye2 lel-ijtima3.',
      state: 'tired',
      tension: 3,
      choices: [
        { id: 'ws5b_sup', ar: 'خلصت المراجعة. إحنا جاهزين.', en: 'Review done. We are ready.', arZ: 'Khalast el-moraja3a. E7na جاهزين.', next: 'ws6' },
        { id: 'ws5b_neu', ar: 'تمام، نختصر ونمشي.', en: 'Okay, keep it short and go.', arZ: 'Tamaam, nkhtaSir w nimshi.', next: 'ws6' },
        { id: 'ws5b_trap', ar: 'إذا تأخرنا مش ذنبي.', en: 'If we are late, not my fault.', arZ: 'Iza ta2akharna mish zanbi.', next: 'ws_end_awk' },
      ],
    },
    ws5r: {
      id: 'ws5r',
      speaker: 'Haneen',
      ar: 'يعني... الضغط جزء من الشغل، مش ضعف.',
      en: 'I mean... pressure is part of work, not weakness.',
      arZ: 'Ya3ni... el-Da8T juz2 men el-shoghl, mish Da3f.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 'ws5r_rep', ar: 'صح، يعطيكي العافية على الثبات.', en: 'Right, thanks for staying steady.', arZ: 'Sa7, ya3teeki el-3afyeh 3al-thabat.', next: 'ws6' },
        { id: 'ws5r_neu', ar: 'تمام، نكمل.', en: 'Okay, continue.', arZ: 'Tamaam, nkammel.', next: 'ws_end_neu' },
      ],
    },
    ws6: {
      id: 'ws6',
      speaker: 'Haneen',
      ar: 'جاهزين. اليوم شغلنا كان مرتب كتير.',
      en: 'We are ready. Today our work was very organized.',
      arZ: 'Jahzeen. El-yom shoghlna kan mratab kteer.',
      state: 'warm',
      tension: 2,
      choices: [
        { id: 'ws6_warm', ar: 'يسعدك. بعد الاجتماع منحتفل بقهوة.', en: 'Great. After meeting we celebrate with coffee.', arZ: 'Yis3dik. Ba3d el-ijtima3 mn7tafel b-ahwe.', next: 'ws_end_warm' },
        { id: 'ws6_neu', ar: 'تمام، على الاجتماع.', en: 'Okay, to the meeting.', arZ: 'Tamaam, 3al-ijtima3.', next: 'ws_end_neu' },
        { id: 'ws6_trap', ar: 'المهم خلصنا بسرعة.', en: 'Important thing we finished quickly.', arZ: 'El-mohem khalasna b-ser3a.', next: 'ws_end_neu' },
      ],
    },
    ws_end_warm: {
      id: 'ws_end_warm',
      speaker: 'Haneen',
      ar: 'اتفقنا. اليوم كان تعاون ممتاز.',
      en: 'Deal. Today collaboration was excellent.',
      arZ: 'Ittafaqna. El-yom kan ta3awon momtaz.',
      state: 'warm',
      tension: 1,
      choices: [{ id: 'ws_end_warm_c', ar: 'دائماً إن شاء الله.', en: 'Always, inshallah.', arZ: 'Dayman inshallah.', next: 'END' }],
    },
    ws_end_neu: {
      id: 'ws_end_neu',
      speaker: 'Haneen',
      ar: 'تمام، كل واحد على مكانه.',
      en: 'Okay, each one to their position.',
      arZ: 'Tamaam, kol wa7ad 3ala makano.',
      state: 'neutral',
      tension: 2,
      choices: [{ id: 'ws_end_neu_c', ar: 'يلا.', en: 'Let us go.', arZ: 'Yalla.', next: 'END' }],
    },
    ws_end_awk: {
      id: 'ws_end_awk',
      speaker: 'Haneen',
      ar: 'طيب... أنا بكمل لحالي.',
      en: 'Okay... I continue alone.',
      arZ: 'Tayyeb... ana بكمل la7ali.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'ws_end_awk_fix', ar: 'استني، آسف. نكمل مع بعض.', en: 'Wait, sorry. Let us continue together.', arZ: 'Istanni, asef. Nkammel ma3 ba3D.', next: 'ws_end_neu' },
        { id: 'ws_end_awk_keep', ar: 'تمام.', en: 'Fine.', arZ: 'Tamaam.', next: 'END' },
      ],
    },
    END: {
      id: 'END',
      speaker: 'System',
      ar: '✅ نهاية المشهد.',
      en: '✅ End of scene.',
      arZ: '✅ Nehayet el-mashhad.',
      state: 'neutral',
      tension: 1,
      choices: [],
    },
  },
};
