import { LESSON_ID_DAILY_ROUTINE } from '../../core/constants.js';

export const dialogueId = 'BD::' + LESSON_ID_DAILY_ROUTINE;

export const dialogue = {
  meta: {
    level: 'Beginner',
    unit: 'Daily Routine',
    title: 'Daily Routine - Morning Workflow Decisions',
    emotionalTracking: true,
    tensionCurve: true,
    trapLayering: true,
    setting: 'Workplace',
  },
  startNodeId: 'd1',
  nodes: {
    d1: {
      id: 'd1',
      speaker: 'Rasha',
      ar: 'صباح الخير أحمد. جاهز لروتين الصبح؟',
      en: 'Good morning Ahmed. Ready for morning routine?',
      arZ: 'Saba7 el-kheir Ahmed. Jahiz le-routine el-sob7?',
      state: 'neutral',
      tension: 1,
      choices: [
        { id: 'd1_sup', ar: 'صباح النور. جاهز، يلا نبدأ.', en: 'Morning. Ready, let us begin.', arZ: 'Saba7 el-noor. Jahiz, yalla nabda.', next: 'd2' },
        { id: 'd1_neu', ar: 'صباح النور. شو أول مهمة؟', en: 'Morning. What is first task?', arZ: 'Saba7 el-noor. Sho awwal mihmeh?', next: 'd2b' },
        { id: 'd1_trap', ar: 'كل يوم نفس الروتين الممل.', en: 'Every day same boring routine.', arZ: 'Kol yom nafs el-routine el-mmall.', next: 'd2c' },
      ],
    },
    d2: {
      id: 'd2',
      speaker: 'Rasha',
      ar: 'آه... أنا نعسانة شوي، بس منلحق.',
      en: 'Ah... I am sleepy a bit, but we can do it.',
      arZ: 'Ah... ana na3saneh shway, bas mnil7a2.',
      state: 'tired',
      tension: 2,
      choices: [
        { id: 'd2_sup', ar: 'خدي نفس، وأنا بفتح النظام أول.', en: 'Take a breath, I open system first.', arZ: 'Khodi nafas, w ana bafta7 el-nizam awwal.', next: 'd3' },
        { id: 'd2_neu', ar: 'تمام، نوزع المهام بسرعة.', en: 'Okay, let us split tasks quickly.', arZ: 'Tamaam, nwazza3 el-mham b-ser3a.', next: 'd3' },
        { id: 'd2_trap', ar: 'القهوة بتحل الموضوع.', en: 'Coffee solves this.', arZ: 'El-ahwe bte7ell el-mawdoo3.', next: 'd2r' },
      ],
    },
    d2b: {
      id: 'd2b',
      speaker: 'Rasha',
      ar: 'بالمناسبة، بدنا نراجع الإيميل ثم اتصال العملاء.',
      en: 'By the way, we review emails then client calls.',
      arZ: 'Belmonasabe, badna nraje3 el-email thomm ittisal el-3omala.',
      state: 'neutral',
      tension: 2,
      choices: [
        { id: 'd2b_sup', ar: 'ممتاز. أنا ببلش بالإيميلات.', en: 'Great. I start emails.', arZ: 'Momtaz. Ana bballesh bel-emails.', next: 'd3' },
        { id: 'd2b_neu', ar: 'تمام، بعدين بنقسم الاتصالات.', en: 'Okay, then we divide calls.', arZ: 'Tamaam, ba3den bn2assem el-ittisalat.', next: 'd3' },
        { id: 'd2b_trap', ar: 'ليش كل هالتفصيل الصبح؟', en: 'Why all this detail in morning?', arZ: 'Leish kol hal-tafseel el-sob7?', next: 'd2r' },
      ],
    },
    d2c: {
      id: 'd2c',
      speaker: 'Rasha',
      ar: 'طيب... الروتين هو اللي بمنع الفوضى.',
      en: 'Okay... routine is what prevents chaos.',
      arZ: 'Tayyeb... el-routine howwe elli byemna3 el-fawDa.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 'd2c_rep', ar: 'معك حق، آسف. خلينا نمشي عليه.', en: 'You are right, sorry. Let us follow it.', arZ: 'Ma3ik 7a2, asef. Khallina nimshi 3aleh.', next: 'd3' },
        { id: 'd2c_neu', ar: 'تمام، أعطيني الخطوات.', en: 'Okay, give me steps.', arZ: 'Tamaam, a3teeni el-khotowat.', next: 'd3' },
      ],
    },
    d2r: {
      id: 'd2r',
      speaker: 'Rasha',
      ar: 'يعني... لو ما رتبنا، بنضيع بنص اليوم.',
      en: 'I mean... without planning, we lose half the day.',
      arZ: 'Ya3ni... law ma rattabna, bniDee3 be-nos el-yom.',
      state: 'stressed',
      tension: 4,
      choices: [
        { id: 'd2r_rep', ar: 'فهمت. يلا نثبت ترتيب واضح.', en: 'Got it. Let us set clear order.', arZ: 'Fehemt. Yalla nthabbit tartib waDe7.', next: 'd3' },
        { id: 'd2r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 'd_end_awk' },
      ],
    },
    d3: {
      id: 'd3',
      speaker: 'Iyad',
      ar: 'مقاطعة: الاجتماع تقدّم نص ساعة.',
      en: 'Interruption: meeting moved 30 minutes earlier.',
      arZ: 'Moqata3a: el-ijtima3 taqaddam noSS sa3a.',
      state: 'stressed',
      tension: 3,
      choices: [
        { id: 'd3_sup', ar: 'تمام، بنقدم المهام العاجلة أول.', en: 'Okay, urgent tasks come first.', arZ: 'Tamaam, bniqaddem el-mham el-3ajleh awwal.', next: 'd4' },
        { id: 'd3_neu', ar: 'منيح، نختصر التقرير الصباحي.', en: 'Good, let us shorten morning report.', arZ: 'Mnee7, nkhtaSir el-taqreer el-Saba7i.', next: 'd4' },
        { id: 'd3_trap', ar: 'مش وقته هالتعديل.', en: 'Bad timing for this change.', arZ: 'Mish wa2to hal-ta3deel.', next: 'd3r' },
      ],
    },
    d3r: {
      id: 'd3r',
      speaker: 'Rasha',
      ar: 'استنى شوي... خلينا نتأقلم بدل التذمر.',
      en: 'Wait... let us adapt instead of complaining.',
      arZ: 'Istanna shway... khallina نتأقلم badal el-tazammor.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'd3r_rep', ar: 'صح، معك حق. بنرتبها هلق.', en: 'Right, you are right. We arrange now.', arZ: 'Sa7, ma3ik 7a2. Bnrattebha halla2.', next: 'd4' },
        { id: 'd3r_neu', ar: 'تمام، شو نلغي أول؟', en: 'Okay, what do we remove first?', arZ: 'Tamaam, sho nlaghi awwal?', next: 'd4' },
      ],
    },
    d4: {
      id: 'd4',
      speaker: 'Rasha',
      ar: 'في طلب صغير: بتراجع نص الرسالة الصباحية؟',
      en: 'Small request: can you review morning message text?',
      arZ: 'Fi talab zghir: btrajje3 naSS el-risaleh el-Saba7iyyeh?',
      state: 'neutral',
      tension: 3,
      choices: [
        { id: 'd4_sup', ar: 'أكيد، ابعتيه فوراً.', en: 'Sure, send it now.', arZ: 'Akeed, eb3ateeh فوراً.', next: 'd5' },
        { id: 'd4_neu', ar: 'بعد دقيقة براجعه.', en: 'I review it after one minute.', arZ: 'Ba3d da2ee2a braje3o.', next: 'd5b' },
        { id: 'd4_trap', ar: 'مش ناقصني تدقيق نصوص.', en: 'I do not need text proofreading now.', arZ: 'Mish na2Sni tadqee2 noSooS.', next: 'd4r' },
      ],
    },
    d4r: {
      id: 'd4r',
      speaker: 'Rasha',
      ar: 'أنا بس طلبت نظرة سريعة... دقيقة بالكثير.',
      en: 'I only asked quick look... one minute max.',
      arZ: 'Ana bas talabt nazra saree3a... da2ee2a bel-kteer.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'd4r_rep', ar: 'معك حق، ابعتيه حالاً.', en: 'You are right, send it now.', arZ: 'Ma3ik 7a2, eb3ateeh 7alan.', next: 'd5' },
        { id: 'd4r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 'd_end_awk' },
      ],
    },
    d5: {
      id: 'd5',
      speaker: 'Rasha',
      ar: 'حلو! الرسالة ممتازة. وبالمناسبة، نبرة التحية لطيفة.',
      en: 'Great! message is excellent. By the way your greeting tone is nice.',
      arZ: '7elw! el-risaleh momtazeh. W belmonasabe, nabret el-ta7iyyeh laTeefeh.',
      state: 'warm',
      tension: 2,
      choices: [
        { id: 'd5_sup', ar: 'يسعدك. لسه بتعلم منكم يومياً.', en: 'Thanks. I still learn daily from you.', arZ: 'Yis3idik. Lissa بت3allam menkom yawmiyyan.', next: 'd6' },
        { id: 'd5_neu', ar: 'تمام، نبعتها قبل الاجتماع.', en: 'Okay, send it before meeting.', arZ: 'Tamaam, نبعتها qabl el-ijtima3.', next: 'd6' },
        { id: 'd5_trap', ar: 'عادي، مش شغل كبير.', en: 'Normal, not a big effort.', arZ: '3adi, mish shoghl kbeer.', next: 'd5r' },
      ],
    },
    d5b: {
      id: 'd5b',
      speaker: 'Rasha',
      ar: 'أوكي... بس الاجتماع قرب كتير.',
      en: 'Okay... but meeting is very close.',
      arZ: 'Okay... bas el-ijtima3 qerib kteer.',
      state: 'tired',
      tension: 3,
      choices: [
        { id: 'd5b_sup', ar: 'خلصت، ابعتي الرسالة.', en: 'Done, send message.', arZ: 'Khalast, eb3ati el-risaleh.', next: 'd6' },
        { id: 'd5b_neu', ar: 'تمام، جاهز للإرسال.', en: 'Okay, ready to send.', arZ: 'Tamaam, jahiz lel-ersal.', next: 'd6' },
        { id: 'd5b_trap', ar: 'إذا تأخرنا مش ذنبي.', en: 'If we are late, not my fault.', arZ: 'Iza ta2akharna mish zanbi.', next: 'd_end_awk' },
      ],
    },
    d5r: {
      id: 'd5r',
      speaker: 'Rasha',
      ar: 'هَه... الكلمة الحلوة كمان جزء من الشغل.',
      en: 'Heh... kind words are also part of work.',
      arZ: 'Hah... el-kalmeh el-7elweh kaman juz2 men el-shoghl.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 'd5r_rep', ar: 'صح، يعطيكي العافية.', en: 'True, thank you.', arZ: 'Sa7, ya3teeki el-3afyeh.', next: 'd6' },
        { id: 'd5r_neu', ar: 'تمام، نكمل.', en: 'Okay, continue.', arZ: 'Tamaam, nkammel.', next: 'd_end_neu' },
      ],
    },
    d6: {
      id: 'd6',
      speaker: 'Rasha',
      ar: 'خلصنا روتين الصبح. اليوم ماشي ممتاز.',
      en: 'Morning routine done. Today is going very well.',
      arZ: 'Khalasna routine el-sob7. El-yom mashi momtaz.',
      state: 'warm',
      tension: 2,
      choices: [
        { id: 'd6_warm', ar: 'ممتاز. بكرا بنمشي أسرع كمان.', en: 'Great. Tomorrow we go even faster.', arZ: 'Momtaz. Bokra bnimshi asra3 kaman.', next: 'd_end_warm' },
        { id: 'd6_neu', ar: 'تمام، على الاجتماع.', en: 'Okay, to the meeting.', arZ: 'Tamaam, 3al-ijtima3.', next: 'd_end_neu' },
        { id: 'd6_trap', ar: 'خلص، المهم خلصنا.', en: 'Done, important is we finished.', arZ: 'Khalas, el-mohem khalasna.', next: 'd_end_neu' },
      ],
    },
    d_end_warm: {
      id: 'd_end_warm',
      speaker: 'Rasha',
      ar: 'يسلمو. بعد الاجتماع قهوة سريعة؟',
      en: 'Thanks. Quick coffee after meeting?',
      arZ: 'Yislamo. Ba3d el-ijtima3 ahwe saree3a?',
      state: 'warm',
      tension: 1,
      choices: [{ id: 'd_end_warm_c', ar: 'أكيد.', en: 'Sure.', arZ: 'Akeed.', next: 'END' }],
    },
    d_end_neu: {
      id: 'd_end_neu',
      speaker: 'Rasha',
      ar: 'تمام، نشوفك بقاعة الاجتماع.',
      en: 'Okay, see you in meeting room.',
      arZ: 'Tamaam, nshoofak b-qa3et el-ijtima3.',
      state: 'neutral',
      tension: 2,
      choices: [{ id: 'd_end_neu_c', ar: 'يلا.', en: 'Let us go.', arZ: 'Yalla.', next: 'END' }],
    },
    d_end_awk: {
      id: 'd_end_awk',
      speaker: 'Rasha',
      ar: 'طيب... كل واحد يشتغل بصمت.',
      en: 'Okay... everyone works in silence.',
      arZ: 'Tayyeb... kol wa7ad yishtighil b-Samt.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'd_end_awk_fix', ar: 'استني، آسف. خلينا نخفف الجو.', en: 'Wait, sorry. Let us soften the mood.', arZ: 'Istanni, asef. Khallina nkhaffef el-jaw.', next: 'd_end_neu' },
        { id: 'd_end_awk_keep', ar: 'تمام.', en: 'Fine.', arZ: 'Tamaam.', next: 'END' },
      ],
    },
    END: {
      id: 'END',
      speaker: 'System',
      ar: '✅ نهاية المشهد.',
      en: '✅ End of scene.',
      arZ: '✅ Nehayet el-mashhad.',
      state: 'neutral',
      tension: 1,
      choices: [],
    },
  },
};
