import { LESSON_ID_FAMILY } from '../../core/constants.js';

export const dialogueId = 'BD::' + LESSON_ID_FAMILY;

export const dialogue = {
  meta: {
    level: 'Beginner',
    unit: 'Family',
    title: 'Family - Shift Planning Decisions',
    emotionalTracking: true,
    tensionCurve: true,
    trapLayering: true,
    setting: 'Workplace',
  },
  startNodeId: 'm1',
  nodes: {
    m1: {
      id: 'm1',
      speaker: 'Salma',
      ar: 'صباح الخير أحمد. بنرتب شفتات الأسبوع؟',
      en: 'Good morning Ahmed. Shall we arrange this week shifts?',
      arZ: 'Saba7 el-kheir Ahmed. Bnratteb shiftat el-osboo3?',
      state: 'neutral',
      tension: 1,
      choices: [
        { id: 'm1_sup', ar: 'صباح النور. أكيد، يلا نبلش.', en: 'Morning. Sure, let us start.', arZ: 'Saba7 el-noor. Akeed, yalla nballesh.', next: 'm2' },
        { id: 'm1_neu', ar: 'صباح النور. شو الأولوية؟', en: 'Morning. What is priority?', arZ: 'Saba7 el-noor. Sho el-awlawiyyeh?', next: 'm2b' },
        { id: 'm1_trap', ar: 'هالجدول مزعج كل أسبوع.', en: 'This schedule is annoying every week.', arZ: 'Hal-jadwal moz3ej kol osboo3.', next: 'm2c' },
      ],
    },
    m2: {
      id: 'm2',
      speaker: 'Salma',
      ar: 'آه... أنا مضغوطة. أمي تعبانة من مبارح.',
      en: 'Ah... I am stressed. My mother is tired since yesterday.',
      arZ: 'Ah... ana maD8ooteh. Emmi ta3baneh men mbar7.',
      state: 'stressed',
      tension: 2,
      choices: [
        { id: 'm2_sup', ar: 'سلامتها. بنبدل شفتك إذا بدك.', en: 'Hope she gets well. We swap your shift if needed.', arZ: 'Salametha. Bnibaddel shiftik iza biddik.', next: 'm3' },
        { id: 'm2_neu', ar: 'تمام، أي أيام بدك تخففي؟', en: 'Okay, which days you need lighter load?', arZ: 'Tamaam, ayyam baddek tkhafffi?', next: 'm3' },
        { id: 'm2_trap', ar: 'كل حدا عنده ظروف.', en: 'Everyone has personal issues.', arZ: 'Kol 7ada 3indo zoroof.', next: 'm2r' },
      ],
    },
    m2b: {
      id: 'm2b',
      speaker: 'Salma',
      ar: 'على سيرة الأهل، عندي ظرف بالبيت يوم الخميس.',
      en: 'Speaking of family, I have a home issue on Thursday.',
      arZ: '3ala seeret el-ahl, 3ندي zarf bel-bait yom el-khamees.',
      state: 'tired',
      tension: 2,
      choices: [
        { id: 'm2b_sup', ar: 'ولا يهمك. بنغطي عنك الخميس.', en: 'No problem. We cover Thursday for you.', arZ: 'Wala yhemmik. BnghaTTi 3annek el-khamees.', next: 'm3' },
        { id: 'm2b_neu', ar: 'تمام، بنعدّل الجدول.', en: 'Okay, we adjust schedule.', arZ: 'Tamaam, bn3addel el-jadwal.', next: 'm3' },
        { id: 'm2b_trap', ar: 'دائماً عندك ظروف.', en: 'You always have issues.', arZ: 'Dayman 3indik zoroof.', next: 'm2r' },
      ],
    },
    m2c: {
      id: 'm2c',
      speaker: 'Salma',
      ar: 'يعني... الجدول مزعج، بس لازم نكون عادلين.',
      en: 'I mean... schedule is tiring, but we must stay fair.',
      arZ: 'Ya3ni... el-jadwal moz3ej, bas lazem nkoon 3adleen.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 'm2c_rep', ar: 'معك حق، آسف. خلينا ننظمه صح.', en: 'You are right, sorry. Let us organize it well.', arZ: 'Ma3ik 7a2, asef. Khallina nnazmo sa7.', next: 'm3' },
        { id: 'm2c_neu', ar: 'تمام، كملي.', en: 'Okay, continue.', arZ: 'Tamaam, kammli.', next: 'm3' },
      ],
    },
    m2r: {
      id: 'm2r',
      speaker: 'Salma',
      ar: 'طيب... ما بدي امتياز. بس مرونة هالأسبوع.',
      en: 'Okay... I do not need privilege, just flexibility this week.',
      arZ: 'Tayyeb... ma biddi imtiyaz. Bas morooneh hal-osboo3.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'm2r_rep', ar: 'فهمت. بنمشي حسب الحاجة.', en: 'Understood. We follow actual need.', arZ: 'Fehemt. Bnimshi 7asab el-7ajeh.', next: 'm3' },
        { id: 'm2r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 'm_end_awk' },
      ],
    },
    m3: {
      id: 'm3',
      speaker: 'Majed',
      ar: 'مقاطعة: المدير سأل عن نسخة الجدول النهائية.',
      en: 'Interruption: manager asked for final schedule copy.',
      arZ: 'Moqata3a: el-mudeer sa2al 3an nuskhat el-jadwal el-niha2iyyeh.',
      state: 'stressed',
      tension: 3,
      choices: [
        { id: 'm3_sup', ar: 'تمام، منبعثها خلال خمس دقايق.', en: 'Okay, we send it in five minutes.', arZ: 'Tamaam, mnib3atha khilal khams da2aye2.', next: 'm4' },
        { id: 'm3_neu', ar: 'منيح، خلينا نثبت الخميس أول.', en: 'Good, let us finalize Thursday first.', arZ: 'Mnee7, khallina nthabbit el-khamees awwal.', next: 'm4' },
        { id: 'm3_trap', ar: 'ينتظر شوي، مش مستعجل.', en: 'He can wait, no rush.', arZ: 'Yentazer shway, mish mista3jel.', next: 'm3r' },
      ],
    },
    m3r: {
      id: 'm3r',
      speaker: 'Salma',
      ar: 'استنى، مبارح تأخرنا وانحرجنا قدامه.',
      en: 'Wait, yesterday we were late and got embarrassed before him.',
      arZ: 'Istanna, mbar7 ta2akharna w en7arajna qoddamo.',
      state: 'stressed',
      tension: 4,
      choices: [
        { id: 'm3r_rep', ar: 'صح، خلينا نخلصها هلق.', en: 'Right, let us finish now.', arZ: 'Sa7, khallina nkhallesha halla2.', next: 'm4' },
        { id: 'm3r_neu', ar: 'تمام، اعطيني التوزيع النهائي.', en: 'Okay, give me final distribution.', arZ: 'Tamaam, a3teeni el-tawzee3 el-niha2i.', next: 'm4' },
      ],
    },
    m4: {
      id: 'm4',
      speaker: 'Salma',
      ar: 'في شغلة صغيرة: بتراجعلي أسماء الشفت الليلي؟',
      en: 'Small thing: can you review night shift names?',
      arZ: 'Fi shaghleh zghireh: btrajje3li asma2 el-shift el-leili?',
      state: 'neutral',
      tension: 3,
      choices: [
        { id: 'm4_sup', ar: 'أكيد، راح أراجعهم الآن.', en: 'Sure, I will review them now.', arZ: 'Akeed, ra7 araje3hom el-aan.', next: 'm5' },
        { id: 'm4_neu', ar: 'بعد دقيقتين ببعث الملاحظات.', en: 'In two minutes I send notes.', arZ: 'Ba3d da2ee2tein bab3ath el-mola7azat.', next: 'm5b' },
        { id: 'm4_trap', ar: 'هاي شغلتك مش شغلتي.', en: 'This is your job not mine.', arZ: 'Hay shoghltek mish shoghlti.', next: 'm4r' },
      ],
    },
    m4r: {
      id: 'm4r',
      speaker: 'Salma',
      ar: 'أنا بس طلبت مساعدة، مش نقل مسؤولية.',
      en: 'I only asked for help, not transferring responsibility.',
      arZ: 'Ana bas talabt msa3adeh, mish na2l mas2ooliyyeh.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'm4r_rep', ar: 'معك حق. آسف، بعملها فوراً.', en: 'You are right. Sorry, I will do it now.', arZ: 'Ma3ik 7a2. Asef, ba3melha فوراً.', next: 'm5' },
        { id: 'm4r_keep', ar: 'اعملي اللي مناسبك.', en: 'Do what suits you.', arZ: 'E3mali elli mnasibik.', next: 'm_end_awk' },
      ],
    },
    m5: {
      id: 'm5',
      speaker: 'Salma',
      ar: 'ممتاز. هيك صرنا عادلين ومراعيين الظروف.',
      en: 'Excellent. Now we are fair and considerate.',
      arZ: 'Momtaz. Heik Sirna 3adleen w mra3yeen el-zoroof.',
      state: 'relaxed',
      tension: 2,
      choices: [
        { id: 'm5_sup', ar: 'هذا المهم. الفريق مثل العيلة.', en: 'That is important. Team is like family.', arZ: 'Hada el-mohem. El-faree2 mithl el-3eeleh.', next: 'm6' },
        { id: 'm5_neu', ar: 'تمام، ابعتي النسخة للمدير.', en: 'Okay, send copy to manager.', arZ: 'Tamaam, eb3ati el-nuskha lel-mudeer.', next: 'm6' },
        { id: 'm5_trap', ar: 'خلص بسرعة وبلا نقاش زيادة.', en: 'Finish quickly with no extra discussion.', arZ: 'Khalas b-ser3a w bala ni2ash ziyadeh.', next: 'm5r' },
      ],
    },
    m5b: {
      id: 'm5b',
      speaker: 'Salma',
      ar: 'أوكي... بس لا نطول، في مراجعة ثانية.',
      en: 'Okay... but let us not delay, there is another review.',
      arZ: 'Okay... bas la n6awwel, fi moraja3a thaniyeh.',
      state: 'tired',
      tension: 3,
      choices: [
        { id: 'm5b_sup', ar: 'تمام، خلصت وراجعت.', en: 'Okay, done and reviewed.', arZ: 'Tamaam, khalast w raja3t.', next: 'm6' },
        { id: 'm5b_neu', ar: 'منيح، جهزي الإرسال.', en: 'Good, prepare sending.', arZ: 'Mnee7, jahhzi el-ersal.', next: 'm6' },
        { id: 'm5b_trap', ar: 'إذا تأخر مش أنا السبب.', en: 'If delayed, I am not reason.', arZ: 'Iza ta2akhar mish ana el-sabab.', next: 'm_end_awk' },
      ],
    },
    m5r: {
      id: 'm5r',
      speaker: 'Salma',
      ar: 'طيب... كنت بحاول أمشيها بروح أحسن.',
      en: 'Okay... I was trying to keep better spirit.',
      arZ: 'Tayyeb... كنت b7awwel amshiha بروح a7san.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 'm5r_rep', ar: 'آسف، خلينا نكمل بهدوء.', en: 'Sorry, let us continue calmly.', arZ: 'Asef, khallina nkammel b-hodoo2.', next: 'm6' },
        { id: 'm5r_neu', ar: 'تمام، منهي الموضوع.', en: 'Okay, done with it.', arZ: 'Tamaam, mnhe el-mawdoo3.', next: 'm_end_neu' },
      ],
    },
    m6: {
      id: 'm6',
      speaker: 'Salma',
      ar: 'انبعت الجدول. يعطيك العافية يا أحمد.',
      en: 'Schedule is sent. Thank you Ahmed.',
      arZ: 'Inba3at el-jadwal. Ya3teek el-3afyeh ya Ahmed.',
      state: 'warm',
      tension: 2,
      choices: [
        { id: 'm6_warm', ar: 'الله يعافيكي. إذا صار ظرف، احكيلي.', en: 'You too. If something happens, tell me.', arZ: 'Allah y3afeeki. Iza sar zarf, e7keeli.', next: 'm_end_warm' },
        { id: 'm6_neu', ar: 'تمام، منشوفك بكرا.', en: 'Okay, see you tomorrow.', arZ: 'Tamaam, mnshoofik bokra.', next: 'm_end_neu' },
        { id: 'm6_trap', ar: 'الموضوع بسيط، ما بده شكر.', en: 'It is simple, no thanks needed.', arZ: 'El-mawdoo3 baseet, ma biddoh shokor.', next: 'm_end_neu' },
      ],
    },
    m_end_warm: {
      id: 'm_end_warm',
      speaker: 'Salma',
      ar: 'متفقين. الله يسعد يومك.',
      en: 'Agreed. Have a great day.',
      arZ: 'Mottafgeen. Allah yis3ed yomak.',
      state: 'warm',
      tension: 1,
      choices: [{ id: 'm_end_warm_c', ar: 'وإنتِ كمان.', en: 'You too.', arZ: 'W enti kaman.', next: 'END' }],
    },
    m_end_neu: {
      id: 'm_end_neu',
      speaker: 'Salma',
      ar: 'تمام، نكمل باقي المهام.',
      en: 'Okay, let us continue remaining tasks.',
      arZ: 'Tamaam, nkammel ba2i el-mham.',
      state: 'neutral',
      tension: 2,
      choices: [{ id: 'm_end_neu_c', ar: 'يلا.', en: 'Let us go.', arZ: 'Yalla.', next: 'END' }],
    },
    m_end_awk: {
      id: 'm_end_awk',
      speaker: 'Salma',
      ar: 'طيب... كل واحد يشتغل لحاله.',
      en: 'Okay... everyone works alone.',
      arZ: 'Tayyeb... kol wa7ad yishtighil la7alo.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 'm_end_awk_fix', ar: 'استني، آسف. خلينا نرجع ننسق.', en: 'Wait, sorry. Let us coordinate again.', arZ: 'Istanni, asef. Khallina يرجع ننasseq.', next: 'm_end_neu' },
        { id: 'm_end_awk_keep', ar: 'تمام.', en: 'Fine.', arZ: 'Tamaam.', next: 'END' },
      ],
    },
    END: {
      id: 'END',
      speaker: 'System',
      ar: '✅ نهاية المشهد.',
      en: '✅ End of scene.',
      arZ: '✅ Nehayet el-mashhad.',
      state: 'neutral',
      tension: 1,
      choices: [],
    },
  },
};
