import { LESSON_ID_TRANSPORT } from '../../core/constants.js';

export const dialogueId = 'BD::' + LESSON_ID_TRANSPORT;

export const dialogue = {
  meta: {
    level: 'Beginner',
    unit: 'trans',
    title: 'Transportation - Commute Decisions',
    emotionalTracking: true,
    tensionCurve: true,
    trapLayering: true,
    setting: 'Workplace',
  },
  startNodeId: 't1',
  nodes: {
    t1: {
      id: 't1',
      speaker: 'Lina',
      ar: 'صباح الخير أحمد. كيف وصلت اليوم؟',
      en: 'Good morning Ahmed. How did you arrive today?',
      arZ: 'Saba7 el-kheir Ahmed. Keef weselt el-yom?',
      state: 'neutral',
      tension: 1,
      choices: [
        { id: 't1_sup', ar: 'صباح النور. جيت بباص الخدمة.', en: 'Morning. I came by service bus.', arZ: 'Saba7 el-noor. Jeet b-bas el-khedmeh.', next: 't2' },
        { id: 't1_neu', ar: 'صباح النور. وصلت بتاكسي.', en: 'Morning. I arrived by taxi.', arZ: 'Saba7 el-noor. Weselt b-taksi.', next: 't2b' },
        { id: 't1_trap', ar: 'ليش هالسؤال كل يوم؟', en: 'Why this question every day?', arZ: 'Leish hal-so2al kol yom?', next: 't2c' },
      ],
    },
    t2: {
      id: 't2',
      speaker: 'Lina',
      ar: 'منيح. أنا اليوم تأخرت بسبب الزحمة.',
      en: 'Good. I was late today because of traffic.',
      arZ: 'Mnee7. Ana el-yom ta2akhkharat b-sabab el-za7meh.',
      state: 'tired',
      tension: 2,
      choices: [
        { id: 't2_sup', ar: 'سلامتك. بدك ننسق مشوار بكرا؟', en: 'Hope you are okay. Shall we coordinate ride tomorrow?', arZ: 'Salamtik. Biddik nnasseq mishwar bokra?', next: 't3' },
        { id: 't2_neu', ar: 'تمام، الطريق كان واقف اليوم.', en: 'Okay, road was blocked today.', arZ: 'Tamaam, el-taree2 kan wa2ef el-yom.', next: 't3' },
        { id: 't2_trap', ar: 'الزحمة حجة جاهزة.', en: 'Traffic is a ready excuse.', arZ: 'El-za7meh 7ojjeh جاهزة.', next: 't2r' },
      ],
    },
    t2b: {
      id: 't2b',
      speaker: 'Lina',
      ar: 'على فكرة، بكرا عنا اجتماع بدري.',
      en: 'By the way, tomorrow we have early meeting.',
      arZ: '3ala fekra, bokra 3inna ijtima3 badri.',
      state: 'neutral',
      tension: 2,
      choices: [
        { id: 't2b_sup', ar: 'ممتاز، نطلع أبكر ونضمن الوصول.', en: 'Great, we leave earlier and guarantee arrival.', arZ: 'Momtaz, n6la3 abkar w nDman el-wosool.', next: 't3' },
        { id: 't2b_neu', ar: 'تمام، بأي ساعة التجمع؟', en: 'Okay, at what time gather?', arZ: 'Tamaam, b-ay sa3a el-tajammo3?', next: 't3' },
        { id: 't2b_trap', ar: 'أنا بجي وقت ما بدي.', en: 'I come whenever I want.', arZ: 'Ana baji wa2et ma biddi.', next: 't2r' },
      ],
    },
    t2c: {
      id: 't2c',
      speaker: 'Lina',
      ar: 'آه... بس بسأل لننسق الطريق مع الفريق.',
      en: 'Ah... I ask only to coordinate transport with team.',
      arZ: 'Ah... bas بسأل la-nnasseq el-taree2 ma3 el-faree2.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 't2c_rep', ar: 'معك حق، آسف. احكيلي الخطة.', en: 'You are right, sorry. Tell me the plan.', arZ: 'Ma3ik 7a2, asef. E7keeli el-khittah.', next: 't3' },
        { id: 't2c_neu', ar: 'تمام، كيف بدنا ننسق؟', en: 'Okay, how do we coordinate?', arZ: 'Tamaam, keef badna nnasseq?', next: 't3' },
      ],
    },
    t2r: {
      id: 't2r',
      speaker: 'Lina',
      ar: 'طيب... كلنا بدنا نوصل بوقت مناسب.',
      en: 'Okay... all of us need to arrive on time.',
      arZ: 'Tayyeb... kollna badna نوصل b-wa2et mnasib.',
      state: 'stressed',
      tension: 4,
      choices: [
        { id: 't2r_rep', ar: 'صح، خلينا نعمل خطة واضحة.', en: 'Right, let us make clear plan.', arZ: 'Sa7, khallina n3mel khittah waDe7eh.', next: 't3' },
        { id: 't2r_keep', ar: 'اعملي اللي بدك.', en: 'Do what you want.', arZ: 'E3mali elli biddik.', next: 't_end_awk' },
      ],
    },
    t3: {
      id: 't3',
      speaker: 'Samer',
      ar: 'مقاطعة: الباص اليوم متأخر ربع ساعة.',
      en: 'Interruption: today bus is late fifteen minutes.',
      arZ: 'Moqata3a: el-bas el-yom mota2akher rob3 sa3a.',
      state: 'stressed',
      tension: 3,
      choices: [
        { id: 't3_sup', ar: 'تمام، منجهز خطة بديلة.', en: 'Okay, we prepare alternative plan.', arZ: 'Tamaam, mnjahhez khittah badeeleh.', next: 't4' },
        { id: 't3_neu', ar: 'منيح، نطلب تاكسي مشترك.', en: 'Good, we order shared taxi.', arZ: 'Mnee7, netlob taksi moshtarak.', next: 't4' },
        { id: 't3_trap', ar: 'خليه يتأخر، مش فارقة.', en: 'Let it be late, no difference.', arZ: 'Khalli ye-ta2akhar, mish fare2a.', next: 't3r' },
      ],
    },
    t3r: {
      id: 't3r',
      speaker: 'Lina',
      ar: 'استنى... الاجتماع مع عميل جديد، الموضوع حساس.',
      en: 'Wait... meeting is with new client, it is sensitive.',
      arZ: 'Istanna... el-ijtima3 ma3 3ameel jdeed, el-mawdoo3 7assas.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 't3r_rep', ar: 'معك حق. يلا نحجز تاكسي الآن.', en: 'You are right. Let us book taxi now.', arZ: 'Ma3ik 7a2. Yalla n7joz taksi el-aan.', next: 't4' },
        { id: 't3r_neu', ar: 'تمام، أي خيار أسرع؟', en: 'Okay, which option is faster?', arZ: 'Tamaam, ay khiyar asra3?', next: 't4' },
      ],
    },
    t4: {
      id: 't4',
      speaker: 'Lina',
      ar: 'في طلب صغير: بتتصل بالسواق وتأكد السعر؟',
      en: 'Small request: call driver and confirm price?',
      arZ: 'Fi talab zghir: btettesel bel-sawwa2 w t2akked el-se3er?',
      state: 'neutral',
      tension: 3,
      choices: [
        { id: 't4_sup', ar: 'أكيد، بثواني بعملها.', en: 'Sure, I do it in seconds.', arZ: 'Akeed, b-thawani ba3melha.', next: 't5' },
        { id: 't4_neu', ar: 'بعد دقيقة بتصير.', en: 'In one minute it is done.', arZ: 'Ba3d da2ee2a btSeer.', next: 't5b' },
        { id: 't4_trap', ar: 'ليش أنا كل مرة أتصل؟', en: 'Why do I call every time?', arZ: 'Leish ana kol marra attesel?', next: 't4r' },
      ],
    },
    t4r: {
      id: 't4r',
      speaker: 'Lina',
      ar: 'أنا طلبت هالمرة بس... لاني عم أرتب المقاعد.',
      en: 'I only asked this time... because I arrange seats.',
      arZ: 'Ana talabt hal-marra bas... la-anni 3am aratteb el-maqa3ed.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 't4r_rep', ar: 'معك حق، آسف. أنا باتصل هلق.', en: 'You are right, sorry. I call now.', arZ: 'Ma3ik 7a2, asef. Ana باتصل halla2.', next: 't5' },
        { id: 't4r_keep', ar: 'اعملي اللي مناسبك.', en: 'Do what suits you.', arZ: 'E3mali elli mnasibik.', next: 't_end_awk' },
      ],
    },
    t5: {
      id: 't5',
      speaker: 'Lina',
      ar: 'ممتاز. السعر مناسب، والسيارة بعد عشر دقايق.',
      en: 'Great. Price is good, car arrives in ten minutes.',
      arZ: 'Momtaz. El-se3er mnasib, w el-sayyara ba3d 3ashr da2aye2.',
      state: 'relaxed',
      tension: 2,
      choices: [
        { id: 't5_sup', ar: 'حلو. بنطلع قبل الزحمة الثانية.', en: 'Nice. We leave before second traffic.', arZ: '7elw. Bn6la3 qabel el-za7meh el-thaniyeh.', next: 't6' },
        { id: 't5_neu', ar: 'تمام، بجهز أغراضي.', en: 'Okay, I prepare my stuff.', arZ: 'Tamaam, bajahhez aghraDi.', next: 't6' },
        { id: 't5_trap', ar: 'كان فينا نوفر المصاري.', en: 'We could have saved money.', arZ: 'Kan feena نوفر el-maSari.', next: 't5r' },
      ],
    },
    t5b: {
      id: 't5b',
      speaker: 'Lina',
      ar: 'أوكي... بس الوقت عم يركض.',
      en: 'Okay... but time is running.',
      arZ: 'Okay... bas el-wa2et 3am yerkod.',
      state: 'tired',
      tension: 3,
      choices: [
        { id: 't5b_sup', ar: 'خلص، حجزت السيارة.', en: 'Done, I booked car.', arZ: 'Khalas, 7jazt el-sayyara.', next: 't6' },
        { id: 't5b_neu', ar: 'تمام، بنطلع فوراً.', en: 'Okay, we leave immediately.', arZ: 'Tamaam, bn6la3 فوراً.', next: 't6' },
        { id: 't5b_trap', ar: 'إذا تأخرنا مش مسؤوليتي.', en: 'If we are late not my responsibility.', arZ: 'Iza ta2akharna mish mas2ooliyti.', next: 't_end_awk' },
      ],
    },
    t5r: {
      id: 't5r',
      speaker: 'Lina',
      ar: 'هههه... بنوفر وقت أهم من المصاري هلق.',
      en: 'Haha... now we save time more than money.',
      arZ: 'Hahaha... bnwaffer wa2et ahamm men el-maSari halla2.',
      state: 'slightly_offended',
      tension: 3,
      choices: [
        { id: 't5r_rep', ar: 'صح، الوقت أغلى اليوم.', en: 'Right, time is more valuable today.', arZ: 'Sa7, el-wa2et aghla el-yom.', next: 't6' },
        { id: 't5r_neu', ar: 'تمام، يلا نتحرك.', en: 'Okay, let us move.', arZ: 'Tamaam, yalla nte7arrak.', next: 't_end_neu' },
      ],
    },
    t6: {
      id: 't6',
      speaker: 'Lina',
      ar: 'وصلنا عالوقت. يعطيك العافية يا أحمد.',
      en: 'We arrived on time. Thanks Ahmed.',
      arZ: 'Wesalna 3al-wa2et. Ya3teek el-3afyeh ya Ahmed.',
      state: 'warm',
      tension: 2,
      choices: [
        { id: 't6_warm', ar: 'الله يعافيكي. بكرا مننسق بدري.', en: 'You too. Tomorrow we coordinate early.', arZ: 'Allah y3afeeki. Bokra mnansseq badri.', next: 't_end_warm' },
        { id: 't6_neu', ar: 'تمام، نطلع عالاجتماع.', en: 'Okay, let us go to meeting.', arZ: 'Tamaam, n6la3 3al-ijtima3.', next: 't_end_neu' },
        { id: 't6_trap', ar: 'المهم وصلنا وخلاص.', en: 'Important is we arrived, done.', arZ: 'El-mohem wesalna w khalas.', next: 't_end_neu' },
      ],
    },
    t_end_warm: {
      id: 't_end_warm',
      speaker: 'Lina',
      ar: 'متفقين. المرة الجاية أنا بحجز من بدري.',
      en: 'Agreed. Next time I will book earlier.',
      arZ: 'Mottafgeen. El-marra el-jayeh ana ba7joz men badri.',
      state: 'warm',
      tension: 1,
      choices: [{ id: 't_end_warm_c', ar: 'ممتاز.', en: 'Excellent.', arZ: 'Momtaz.', next: 'END' }],
    },
    t_end_neu: {
      id: 't_end_neu',
      speaker: 'Lina',
      ar: 'تمام، نكمل يومنا.',
      en: 'Okay, let us continue our day.',
      arZ: 'Tamaam, nkammel yomna.',
      state: 'neutral',
      tension: 2,
      choices: [{ id: 't_end_neu_c', ar: 'يلا.', en: 'Let us go.', arZ: 'Yalla.', next: 'END' }],
    },
    t_end_awk: {
      id: 't_end_awk',
      speaker: 'Lina',
      ar: 'طيب... كل واحد يدبر مواصلاته.',
      en: 'Okay... everyone handles their own transport.',
      arZ: 'Tayyeb... kol wa7ad ydabber muwasalato.',
      state: 'slightly_offended',
      tension: 4,
      choices: [
        { id: 't_end_awk_fix', ar: 'استني، آسف. خلينا نكمل تنسيق.', en: 'Wait, sorry. Let us keep coordinating.', arZ: 'Istanni, asef. Khallina nkammel tanseeq.', next: 't_end_neu' },
        { id: 't_end_awk_keep', ar: 'تمام.', en: 'Fine.', arZ: 'Tamaam.', next: 'END' },
      ],
    },
    END: {
      id: 'END',
      speaker: 'System',
      ar: '✅ نهاية المشهد.',
      en: '✅ End of scene.',
      arZ: '✅ Nehayet el-mashhad.',
      state: 'neutral',
      tension: 1,
      choices: [],
    },
  },
};
